In [1]:
import numpy as np

In [2]:
X = np.array([[1, 2, 3, 4], [4, 5, 6, 4], [7, 8, 9, 4]])
filter1 = np.array([[3, 2, 0], [3, 0, 1], [0, 5, 2], [1, 1, 1]])

In [3]:
np.dot(X, filter1)

array([[13, 21, 12],
       [31, 42, 21],
       [49, 63, 30]])

In [4]:
X @ filter1

array([[13, 21, 12],
       [31, 42, 21],
       [49, 63, 30]])

In [5]:
import tensorflow as tf

In [6]:
tf.multiply(X, filter1)

2026-01-05 05:40:36.538234: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: INVALID_ARGUMENT: Incompatible shapes: [3,4] vs. [4,3]


InvalidArgumentError: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3,4] vs. [4,3] [Op:Mul]

In [7]:
tf.matmul(X, filter1)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[13, 21, 12],
       [31, 42, 21],
       [49, 63, 30]])>

In [8]:
x = tf.random.uniform([3, 3])

# print("Is there a GPU available: "),
# print(tf.config.list_physical_devices("GPU"))
#
# print("Is the Tensor on GPU #0:  "),
# print(x.device.endswith("MPS:0"))

In [13]:
# tf.config.list_physical_devices("MPS")

[]

In [ ]:
import tensorflow as tf

cifar = tf.keras.datasets.cifar100
(x_train, y_train), (x_test, y_test) = cifar.load_data()
model = tf.keras.applications.ResNet50(
    include_top=True,
    weights=None,
    input_shape=(32, 32, 3),
    classes=100,
)

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False)
model.compile(optimizer="adam", loss=loss_fn, metrics=["accuracy"])
model.fit(x_train, y_train, epochs=5, batch_size=64)

169001437/169001437 ━━━━━━━━━━━━━━━━━━━━ 40s 0us/step
Epoch 1/5
165/782 ━━━━━━━━━━━━━━━━━━━━ 4:50 472ms/step - accuracy: 0.0214 - loss: 5.7306