In [1]:
from numpy import dtype

!pip install keras

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras as ks

In [3]:
df = pd.read_csv("./d5fe9cfa-3637-4844-9c69-2ea989db999e-house-price-full-1-.csv")

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
scaler = StandardScaler()

In [8]:
df

,bedrooms,sqft_living,price
0,3,1340,313000
1,5,3650,2384000
2,3,1930,342000
3,3,2000,420000
4,4,1940,550000
...,...,...,...
494,4,3040,647000
495,5,4530,950000
496,3,1370,185000
497,3,1940,335000


In [9]:
y = df.pop("price")
X = df

In [10]:
y

0       313000
1      2384000
2       342000
3       420000
4       550000
        ...   
494     647000
495     950000
496     185000
497     335000
498     210000
Name: price, Length: 499, dtype: int64

In [11]:
X = scaler.fit_transform(X)
y = np.log(y)

In [13]:
model = ks.Sequential(
    [
        ks.layers.Dense(2, activation="sigmoid", input_shape=(X.shape[-1], 1)),
        ks.layers.Dense(1, activation="linear"),
    ]
)
model.summary()

C:\Users\ak007\anaconda4\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2, 2)           │             4 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 2, 1)           │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7 (28.00 B)

 Trainable params: 7 (28.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.compile(optimizer=ks.optimizers.SGD(), loss="mean_squared_error")

In [16]:
model.fit(X, y.values, epochs=10, batch_size=32)

Epoch 1/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 100.3756  
Epoch 2/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.6587 
Epoch 3/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.0587 
Epoch 4/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8284 
Epoch 5/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3422 
Epoch 6/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2721 
Epoch 7/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2627 
Epoch 8/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2604 
Epoch 9/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2603 
Epoch 10/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2603 


In [17]:
model.predict(X)[:, 0]

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


array([[13.076382],
       [13.162939],
       [13.076382],
       [13.076382],
       [13.135398],
       [12.983355],
       [12.983355],
       [13.135398],
       [13.076382],
       [13.135398],
       [13.076382],
       [13.135398],
       [13.076382],
       [13.076382],
       [13.162939],
       [13.076382],
       [13.076382],
       [13.135398],
       [13.076382],
       [13.076382],
       [13.076382],
       [13.135398],
       [13.076382],
       [13.135398],
       [13.135398],
       [13.076382],
       [13.076382],
       [13.135398],
       [13.162939],
       [13.076382],
       [13.135398],
       [13.135398],
       [13.135398],
       [13.135398],
       [13.135398],
       [13.076382],
       [12.983355],
       [13.076382],
       [13.076382],
       [13.076382],
       [13.076382],
       [13.135398],
       [12.983355],
       [13.076382],
       [12.983355],
       [13.076382],
       [13.076382],
       [13.076382],
       [13.076382],
       [13.135398],


a##Question##

Solve the following system of linear equations using TensorFlow:

x + y + z + w = 13

2x + 3y − w = −1

−3x + 4y + z + 2w = 10

x + 2y − z + w = 1

Ans: x = 2, y = 0, z = 6 , w = 5

In [12]:
import tensorflow as tf

In [23]:
W = tf.Variable(
    [[1, 1, 1, 1], [2, 3, 0, -1], [-3, 4, 1, 2], [1, 2, -1, 1]], dtype=tf.float32
)
y = tf.Variable([[13], [-1], [10], [1]], dtype=tf.float32)
W = tf.linalg.inv(W)

In [24]:
X = tf.cast(tf.round(tf.matmul(W, y)), dtype=tf.int32)

In [25]:
X

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[2],
       [0],
       [6],
       [5]])>