In [1]:
import numpy as np
import pandas as pd
import torch
import tensorflow as tf

In [2]:
import os

os.environ["KERAS_TELEMETRY"] = "0"

In [2]:
x = np.array([1, 2, 3, 4])
torch.from_numpy(x)

tensor([1, 2, 3, 4])

In [9]:
a1 = tf.Variable(x)

In [89]:
a1[2]

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [10]:
a2 = tf.constant(x)

In [11]:
dir(a1)

['SaveSliceInfo',
 '_OverloadAllOperators',
 '_OverloadOperator',
 '_TensorConversionFunction',
 '__abs__',
 '__abstractmethods__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__complex__',
 '__composite_gradient__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ipow__',
 '__irealdiv__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '

In [7]:
dir(a2)

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__complex__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclass

In [12]:
m = tf.Module()
m.v = tf.Variable(x)

In [13]:
m

In [14]:
dir(m)

['_TF_MODULE_IGNORED_PROPERTIES',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_trackable_child',
 '_add_variable_with_custom_getter',
 '_checkpoint_adapter',
 '_checkpoint_dependencies',
 '_copy_trackable_to_cpu',
 '_deferred_dependencies',
 '_delete_tracking',
 '_deserialization_dependencies',
 '_deserialize_from_proto',
 '_export_to_saved_model_graph',
 '_flatten',
 '_gather_saveables_for_checkpoint',
 '_handle_deferred_dependencies',
 '_lookup_dependency',
 '_maybe_initialize_trackable',
 '_name',
 '_name_based_attribute_restore',
 '_name_based_restores',
 '_name_scope',
 '_no_dependency',
 '_object_identifier',
 '_preload_simple_restoratio

In [21]:
m.matrix_cn = tf.constant([list(range(10)), list(range(1, 20, 2))])

In [41]:
m.matrix_cn

<tf.Tensor: shape=(2, 10), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]], dtype=int32)>

In [28]:
m.t = tf.Variable(
    [
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
    ]
)
m.t_other = tf.Variable([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14]])

In [29]:
tf.transpose(m.t)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]], dtype=int32)>

In [34]:
m.multiplied = tf.linalg.matmul(m.t, m.t_other)

In [38]:
m.trainable_variables

(<tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(5, 3) dtype=int32, numpy=
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(4,) dtype=int64, numpy=array([1, 2, 3, 4])>)

In [40]:
m.t + m.t

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]], dtype=int32)>

In [43]:
m.t1 = tf.cast(m.t, tf.float32)

In [59]:
tf.linalg.det(m.t1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [45]:
m.t1_inv = tf.linalg.inv(m.t1)

W0000 00:00:1777728676.693890  609194 local_rendezvous.cc:412] Local rendezvous is aborting with status: INVALID_ARGUMENT: Input is not invertible.


InvalidArgumentError: {{function_node __wrapped__MatrixInverse_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input is not invertible. [Op:MatrixInverse] name: 

In [85]:
m.x = tf.cast(tf.Variable([[2, 3], [2, 2]]), tf.float32)

In [86]:
tf.linalg.det(m.x)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [87]:
tf.linalg.eigh(m.x)

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.       , 3.9999998], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.70710677,  0.70710677],
        [ 0.70710677,  0.70710677]], dtype=float32)>)

In [57]:
len(m.trainable_variables)

3

In [58]:
len(m.variables)

3

In [60]:
def inverse(x):
   return "Inverse Not possible"  if x

In [61]:
inverse(m.x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1. ,  1.5],
       [ 1. , -1. ]], dtype=float32)>

In [76]:
inverse(inverse(m.x))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [2., 2.]], dtype=float32)>

In [69]:
inverse(m.t_other)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: half, float, double, complex64, complex128
	; NodeDef: {{node MatrixDeterminant}}; Op<name=MatrixDeterminant; signature=input:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixDeterminant] name: 

In [65]:
m.t_other

<tf.Variable 'Variable:0' shape=(5, 3) dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]], dtype=int32)>


In [68]:
np.linalg.det(
    [
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
    ]
)

np.float64(0.0)

In [77]:
x = tf.Variable(
    [[3, 2, 4], [2, 0, 2], [4, 2, 3]], dtype=tf.float32
)  # raises exception if datatype is not floatX

In [78]:
inverse(x)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.5  ,  0.25 ,  0.5  ],
       [ 0.25 , -0.875,  0.25 ],
       [ 0.5  ,  0.25 , -0.5  ]], dtype=float32)>

In [79]:
eigen_values, eigen_vectors = tf.linalg.eigh(x)

In [80]:
eigen_values

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-1.0000002, -0.9999995,  8.000001 ], dtype=float32)>

In [81]:
eigen_vectors

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.74535596,  0.        ,  0.66666675],
       [ 0.2981424 , -0.8944272 ,  0.33333328],
       [ 0.59628487,  0.4472136 ,  0.6666666 ]], dtype=float32)>

In [83]:
x = tf.cast(x, tf.float32)

In [84]:
inverse(x)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.5  ,  0.25 ,  0.5  ],
       [ 0.25 , -0.875,  0.25 ],
       [ 0.5  ,  0.25 , -0.5  ]], dtype=float32)>

In [98]:
x = tf.Variable(3, dtype=tf.float32)

with tf.GradientTape() as tape:
    y = 3 * tf.math.log(x)

In [99]:
dy_dx = tape.gradient(y, x)

In [100]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [137]:
num_features = 10  # the model has 10 features
W = tf.Variable(
    tf.random.normal(shape=(10,))
)  # wrapping the random numbers with tf.Variable to enable gradients on W
b = tf.Variable(
    tf.random.normal(shape=(1,))
)  # wrapping the random numbers with tf.Variable to enable gradients on b

# let us initialize a training samples
num_samples = 100

# generate training samples randomly and wrap them up in tf.constant to disable gradient computation on samples
X = tf.constant(tf.random.uniform(shape=(100, 10)))
y = tf.constant(
    tf.cast(tf.greater(tf.random.uniform(shape=(100,)), 0.80), dtype=tf.float32)
)  # target must be 0 and 1

In [104]:
tf.constant(
    tf.cast(tf.greater(tf.random.uniform(shape=(100,)), 0.80), dtype=tf.float32)
)

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
      dtype=float32)>

In [112]:
x = tf.cast(tf.constant([1.8, 2.2], dtype=tf.float32), dtype=tf.float32)

In [116]:
tf.Variable((tf.greater(x, 0.9)), dtype=tf.float32)

ValueError: initial_value: Tensor conversion requested dtype float32 for Tensor with dtype bool: <tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

In [117]:
tf.cast(tf.greater(tf.random.uniform(shape=(100,)), 0.80), dtype=tf.float32)

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0.],
      dtype=float32)>

In [129]:
x = tf.random.uniform(shape=(20,))

In [130]:
x  #

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([0.5475091 , 0.1839639 , 0.8968512 , 0.8279604 , 0.24320614,
       0.17820227, 0.8308408 , 0.37748718, 0.36513507, 0.02467811,
       0.52840066, 0.20810199, 0.04221094, 0.5805583 , 0.31925488,
       0.44550645, 0.06729722, 0.7682146 , 0.22977066, 0.66311586],
      dtype=float32)>

In [133]:
np.max(x)

np.float32(0.8968512)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.], dtype=float32)>

In [187]:
def loss_fn_classify_binary(W, X, y, b):
    try:
        with tf.GradientTape() as tape:
            log_odds = tf.reduce_sum(W * X, axis=1) + b
            # tf.reduce_sum(W * X, axis=1) results in a (1, ) vector to which b is added

            probabilities = tf.sigmoid(log_odds)

            loss = tf.reduce_mean(
                -y * tf.math.log(probabilities)
                - (1.0 - y) * tf.math.log(1 - probabilities)
            )
        a, b = tape.gradient(loss, [W, b])
        return f"Output:{a.numpy()}, Bias:{b.numpy()}"
    except Exception as e:
        return "None type has no gradient"

In [188]:
loss_fn_classify_binary(W, X, y, b)

"Output:f[0.35504857 0.29912195 0.29865444 0.32677    0.32973218 0.30001175\n 0.2851465  0.30763054 0.30287713 0.34030366],'\n' Bias:[0.6474393]"

In [174]:
dloss_W, dloss_b = loss_fn(W, X, y, b)

In [175]:
dloss_W.numpy()

array([0.35504857, 0.29912195, 0.29865444, 0.32677   , 0.32973218,
       0.30001175, 0.2851465 , 0.30763054, 0.30287713, 0.34030366],
      dtype=float32)

In [176]:
dloss_b.numpy()

array([0.6474393], dtype=float32)

In [143]:
tf.reduce_sum(W * X, axis=1) + b

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([ 2.1605737 ,  2.214447  ,  1.9106767 ,  2.921413  ,  4.645369  ,
        3.5439854 ,  0.8328124 ,  3.126761  ,  0.64012235,  2.4794888 ,
        4.3256598 ,  2.0096874 ,  2.4801989 ,  4.7555695 ,  2.9166944 ,
        2.488591  ,  0.9298527 ,  1.0410805 ,  1.3530645 ,  2.3224244 ,
        2.880628  ,  1.744169  ,  3.3218417 ,  3.1308403 ,  3.9402487 ,
        3.465112  ,  3.2784512 ,  3.326749  ,  2.259814  ,  4.2042027 ,
        1.0993537 ,  2.4855213 ,  1.3993003 ,  4.790546  ,  2.325904  ,
        1.5223207 ,  3.7612133 ,  2.9161866 ,  3.168604  ,  0.52177256,
        3.4197593 ,  3.37966   ,  1.9545754 ,  0.94393504,  2.2128024 ,
        2.293478  ,  1.9495457 ,  1.4843943 ,  1.3950796 ,  3.3252316 ,
        2.8144243 ,  2.4634094 ,  0.13418919,  1.6971624 ,  0.6622439 ,
        4.3954935 ,  2.997137  ,  1.7443134 ,  3.2132063 ,  2.4501128 ,
        1.9279463 ,  0.7971065 ,  1.8079104 ,  0.9963743 ,  3.5051847 ,
        2.742246

In [145]:
tape.gradient()

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([ 2.1605737 ,  2.214447  ,  1.9106767 ,  2.921413  ,  4.645369  ,
        3.5439854 ,  0.8328124 ,  3.126761  ,  0.64012235,  2.4794888 ,
        4.3256598 ,  2.0096874 ,  2.4801989 ,  4.7555695 ,  2.9166944 ,
        2.488591  ,  0.9298527 ,  1.0410805 ,  1.3530645 ,  2.3224244 ,
        2.880628  ,  1.744169  ,  3.3218417 ,  3.1308403 ,  3.9402487 ,
        3.465112  ,  3.2784512 ,  3.326749  ,  2.259814  ,  4.2042027 ,
        1.0993537 ,  2.4855213 ,  1.3993003 ,  4.790546  ,  2.325904  ,
        1.5223207 ,  3.7612133 ,  2.9161866 ,  3.168604  ,  0.52177256,
        3.4197593 ,  3.37966   ,  1.9545754 ,  0.94393504,  2.2128024 ,
        2.293478  ,  1.9495457 ,  1.4843943 ,  1.3950796 ,  3.3252316 ,
        2.8144243 ,  2.4634094 ,  0.13418919,  1.6971624 ,  0.6622439 ,
        4.3954935 ,  2.997137  ,  1.7443134 ,  3.2132063 ,  2.4501128 ,
        1.9279463 ,  0.7971065 ,  1.8079104 ,  0.9963743 ,  3.5051847 ,
        2.742246

In [21]:
help(tf.keras.layers.Layer)

Help on class Layer in module keras.src.layers.layer:

class Layer(keras.src.backend.tensorflow.layer.TFLayer, keras.src.ops.operation.Operation)
 |  Layer(*args, **kwargs)
 |
 |  This is the class from which all layers inherit.
 |
 |  A layer is a callable object that takes as input one or more tensors and
 |  that outputs one or more tensors. It involves *computation*, defined
 |  in the `call()` method, and a *state* (weight variables). State can be
 |  created:
 |
 |  * in `__init__()`, for instance via `self.add_weight()`;
 |  * in the optional `build()` method, which is invoked by the first
 |    `__call__()` to the layer, and supplies the shape(s) of the input(s),
 |    which may not have been known at initialization time.
 |
 |  Layers are recursively composable: If you assign a Layer instance as an
 |  attribute of another Layer, the outer layer will start tracking the weights
 |  created by the inner layer. Nested layers should be instantiated in the
 |  `__init__()` method o

In [1]:
from tensorflow import keras
from keras import layers

In [2]:
model = keras.Sequential(
    [
        layers.Dense(units=32, input_shape=(8,)),
        layers.Dense(32, activation="relu"),
        layers.Dense(1),
    ]
)

/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [3]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,377 (5.38 KB)

 Trainable params: 1,377 (5.38 KB)

 Non-trainable params: 0 (0.00 B)

In [5]:
import tensorflow as tf

In [6]:
layer1 = layers.Dense(units=3, actication=tf.nn.relu)
layer2 = layers.Dense(units=3, activation=tf.nn.relu)
layer3 = layers.Dense(units=4)

In [18]:
x = tf.random.normal((10, 10))
y = layer3(layer2(layer1(x)))

In [19]:
layer1.get_weights()

[array([[-0.25326893,  0.3564924 , -0.3996747 ],
        [ 0.34033406, -0.43536493,  0.02376103],
        [ 0.02422637, -0.07656783,  0.2748801 ],
        [-0.43267357,  0.51491106, -0.63995725],
        [ 0.32542992,  0.64928985,  0.08466321],
        [-0.19075915, -0.13150585, -0.3507545 ],
        [-0.44371045,  0.20038831, -0.43704087],
        [-0.3908313 , -0.23434427, -0.5687027 ],
        [ 0.02440536, -0.12825388, -0.381488  ],
        [-0.23396769,  0.56593454, -0.11671358]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [16]:
model = keras.Sequential()

model.add(layer1)
model.add(layer2)
model.add(layer3)

In [20]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (10, 3)                │            33 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (10, 3)                │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (10, 4)                │            16 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 61 (244.00 B)

 Trainable params: 61 (244.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
layer_a = tf.keras.layers.Dense(1, kernel_initializer=tf.constant_initializer(1.0))
layer_a.get_weights()

[]

In [8]:
model.get_config()

{'name': 'sequential_1',
 'trainable': True,
 'dtype': {'module': 'keras',
  'class_name': 'DTypePolicy',
  'config': {'name': 'float32'},
  'registered_name': None},
 'layers': [{'module': 'keras.layers',
   'class_name': 'InputLayer',
   'config': {'batch_shape': (None, 8),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'input_layer_1',
    'optional': False},
   'registered_name': None},
  {'module': 'keras.layers',
   'class_name': 'Dense',
   'config': {'name': 'dense_3',
    'trainable': True,
    'dtype': {'module': 'keras',
     'class_name': 'DTypePolicy',
     'config': {'name': 'float32'},
     'registered_name': None},
    'units': 32,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'module': 'keras.initializers',
     'class_name': 'GlorotUniform',
     'config': {'seed': None},
     'registered_name': None},
    'bias_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
    

In [17]:
layer = layers.Activation("relu")
help(layer)

Help on Activation in module keras.src.layers.activations.activation object:

class Activation(keras.src.layers.layer.Layer)
 |  Activation(activation, **kwargs)
 |
 |  Applies an activation function to an output.
 |
 |  Args:
 |      activation: Activation function. It could be a callable, or the name of
 |          an activation from the `keras.activations` namespace.
 |      **kwargs: Base layer keyword arguments, such as `name` and `dtype`.
 |
 |  Example:
 |
 |  >>> layer = keras.layers.Activation('relu')
 |  >>> layer(np.array([-3.0, -1.0, 0.0, 2.0]))
 |  [0.0, 0.0, 0.0, 2.0]
 |  >>> layer = keras.layers.Activation(keras.activations.relu)
 |  >>> layer(np.array([-3.0, -1.0, 0.0, 2.0]))
 |  [0.0, 0.0, 0.0, 2.0]
 |
 |  Method resolution order:
 |      Activation
 |      keras.src.layers.layer.Layer
 |      keras.src.backend.tensorflow.layer.TFLayer
 |      keras.src.backend.tensorflow.trackable.KerasAutoTrackable
 |      tensorflow.python.trackable.autotrackable.AutoTrackable
 |   

Help on class Activation in module keras.src.layers.activations.activation:

class Activation(keras.src.layers.layer.Layer)
 |  Activation(activation, **kwargs)
 |
 |  Applies an activation function to an output.
 |
 |  Args:
 |      activation: Activation function. It could be a callable, or the name of
 |          an activation from the `keras.activations` namespace.
 |      **kwargs: Base layer keyword arguments, such as `name` and `dtype`.
 |
 |  Example:
 |
 |  >>> layer = keras.layers.Activation('relu')
 |  >>> layer(np.array([-3.0, -1.0, 0.0, 2.0]))
 |  [0.0, 0.0, 0.0, 2.0]
 |  >>> layer = keras.layers.Activation(keras.activations.relu)
 |  >>> layer(np.array([-3.0, -1.0, 0.0, 2.0]))
 |  [0.0, 0.0, 0.0, 2.0]
 |
 |  Method resolution order:
 |      Activation
 |      keras.src.layers.layer.Layer
 |      keras.src.backend.tensorflow.layer.TFLayer
 |      keras.src.backend.tensorflow.trackable.KerasAutoTrackable
 |      tensorflow.python.trackable.autotrackable.AutoTrackable
 |    

In [12]:
out = layer(np.array([-3.0, -1.0, 0.0, 2.0]))

In [14]:
layer = keras.layers.Activation(keras.activations.relu)