# Housing and mnist
##  BackPropogation using SGD and moment of methods from scratch

In [1]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [210]:
import os

os.environ["KERAS_TELEMETRY"] = "0"

In [2]:
df = pd.read_csv("data/house-price.csv")

In [3]:
df

,bedrooms,sqft_living,price
0,3,1340,313000
1,5,3650,2384000
2,3,1930,342000
3,3,2000,420000
4,4,1940,550000
...,...,...,...
494,4,3040,647000
495,5,4530,950000
496,3,1370,185000
497,3,1940,335000


In [4]:
df["bedrooms"].value_counts()

bedrooms
3    215
4    163
2     69
5     41
6      5
7      3
1      2
9      1
Name: count, dtype: int64

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   bedrooms     499 non-null    int64
 1   sqft_living  499 non-null    int64
 2   price        499 non-null    int64
dtypes: int64(3)
memory usage: 11.8 KB


In [8]:
columns = df.columns.tolist()

In [18]:
target = "price"
X = df[[col for col in columns if col != "price"]]
y = df[target]

In [19]:
y

0       313000
1      2384000
2       342000
3       420000
4       550000
        ...   
494     647000
495     950000
496     185000
497     335000
498     210000
Name: price, Length: 499, dtype: int64

## Implementing train test split

In [93]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, test_size=0.3
)

In [94]:
len(X_train), len(X_test)

(349, 150)

In [116]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [117]:
scaler = StandardScaler()
X_train_model = scaler.fit_transform(X_train)
X_test_model = scaler.transform(X_test)

In [118]:
X_train_model

array([[ 0.57439495,  1.23247013],
       [ 2.57903333,  1.20592658],
       [-0.42792424, -0.1300989 ],
       [-0.42792424, -0.6698178 ],
       [ 0.57439495, -0.20972956],
       [ 0.57439495,  1.02896956],
       [ 0.57439495, -0.6698178 ],
       [-0.42792424, -0.05046824],
       [-0.42792424,  0.9670346 ],
       [-0.42792424,  0.40077215],
       [-0.42792424, -0.57249144],
       [ 0.57439495,  0.84316469],
       [-0.42792424,  0.18842373],
       [ 0.57439495,  0.49809851],
       [ 1.57671414,  2.69236552],
       [-1.43024343, -1.1564496 ],
       [-0.42792424, -0.26281666],
       [-1.43024343, -0.98834043],
       [-0.42792424, -0.01507684],
       [ 1.57671414,  0.92279535],
       [ 0.57439495, -0.12125105],
       [-1.43024343, -0.81138341],
       [ 0.57439495, -0.1300989 ],
       [-0.42792424, -0.5096717 ],
       [-0.42792424, -0.73175276],
       [-0.42792424,  0.43616355],
       [-1.43024343, -0.88216622],
       [-0.42792424, -0.81138341],
       [-0.42792424,

In [119]:
y_train

461     800000
356    1750000
3       420000
399     280950
380     835000
        ...   
106     501000
270     492000
348     350000
435     315000
102     787000
Name: price, Length: 349, dtype: int64

In [120]:
y_train_model = np.log(y_train)

In [121]:
y_train_model

461    13.592367
356    14.375126
3      12.948010
399    12.545932
380    13.635187
         ...    
106    13.124361
270    13.106234
348    12.765688
435    12.660328
102    13.575984
Name: price, Length: 349, dtype: float64

In [34]:
lm = LinearRegression()
lm.fit(X_train_model, y_train_model)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [122]:
# Log again because fitted on log of y_train
y_test_model = np.log(y_test)

In [35]:
pred = lm.predict(X_test_model)

In [36]:
pred

array([12.83386872, 13.00805907, 12.72499975, 12.99250636, 12.76232625,
       12.85875305, 12.88052685, 13.01540705, 13.36491464, 12.89098537,
       12.99164961, 13.19892902, 13.04029138, 13.07960153, 13.04227503,
       12.86652941, 13.16471306, 12.90342754, 13.04340192, 13.19072429,
       13.17206104, 12.67099364, 12.72499975, 13.12738656, 13.20713375,
       13.14803345, 12.8027633 , 13.5546577 , 13.26736094, 13.24955444,
       13.59396784, 13.09317059, 13.02050123, 13.01739069, 12.98119109,
       13.19158104, 13.27047148, 13.14325032, 12.85564251, 12.85564251,
       12.9738431 , 12.8400898 , 13.29535582, 12.89495266, 12.83386872,
       13.32646124, 13.10024843, 12.93029552, 13.14604981, 13.0329434 ,
       12.67099364, 12.97073256, 13.60329947, 12.6678831 , 12.84320034,
       13.12738656, 12.98826892, 13.36378774, 13.08072843, 13.0329434 ,
       13.09099322, 13.16047562, 13.03916448, 13.32447759, 13.04849611,
       12.83697926, 13.44155129, 13.2051501 , 13.09006005, 13.69

In [42]:
# precision recall guessing when classification

sklearn.metrics.mean_squared_error(y_test_model, pred)

0.1413195662325988

# Part 2 using tensorflow

In [92]:
X_train_model.shape

(279, 2)

In [ ]:
X_train_val, X_test_, y_train_val, y_test_val = train_test_split(
    X_train_model, y_train_model, test_size=0.2
)

In [44]:
from tensorflow.keras import layers
from tensorflow import keras

In [55]:
X_train_model.shape[1]

2

In [123]:
model = tf.keras.Sequential()
model.add(layers.Input(shape=(X_train_model.shape[-1],), name="input_layer"))
model.add(layers.Dense(units=20, activation=tf.nn.relu, name="layer_1"))
model.add(layer=layers.Dense(units=10, activation=tf.nn.relu, name="layer_2"))
model.add(layer=layers.Dense(units=1, activation="linear", name="output_fn"))

In [80]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer_1 (Dense)                 │ (None, 20)             │            60 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer_2 (Dense)                 │ (None, 10)             │           210 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_fn (Dense)               │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 281 (1.10 KB)

 Trainable params: 281 (1.10 KB)

 Non-trainable params: 0 (0.00 B)

In [126]:
model.compile(
    optimizer=tf.optimizers.SGD(learning_rate=0.1),  # todo build from scratch
    loss=tf.losses.MeanSquaredError,
    metrics=[tf.metrics.MAE],
)

In [106]:
type(y_train_model)

pandas.Series

In [127]:
model.fit(X_train_model, y_train_model.values, epochs=10)

Epoch 1/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - loss: 4494.9873 - mean_absolute_error: 21.3709
Epoch 2/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 60.0778 - mean_absolute_error: 6.4296  
Epoch 3/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - loss: 0.7115 - mean_absolute_error: 0.6668
Epoch 4/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - loss: 0.2736 - mean_absolute_error: 0.4074
Epoch 5/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2711 - mean_absolute_error: 0.4081
Epoch 6/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - loss: 0.2723 - mean_absolute_error: 0.4087
Epoch 7/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2713 - mean_absolute_error: 0.4067
Epoch 8/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - loss: 0.2716 - mean_absolute_error: 0.4074
Epoch 9/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - loss: 0.2712 - mean_absolute_error: 0.4078
Epoch 10/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - loss: 0.2727 - mean_absolute_error: 0.4083


In [69]:
history = model.history.history

In [109]:
pd.DataFrame(history)

,loss,mean_absolute_error
0,633.776428,13.496337
1,2.175801,1.202627
2,0.283443,0.419469
3,0.271344,0.407128
4,0.271573,0.407556
5,0.271539,0.406708
6,0.271963,0.407462
7,0.271543,0.406999
8,0.271441,0.406981
9,0.271925,0.408000


In [110]:
np.min(history["loss"])

np.float64(0.2713443338871002)

In [111]:
model.get_config()

{'name': 'sequential_7',
 'trainable': True,
 'dtype': {'module': 'keras',
  'class_name': 'DTypePolicy',
  'config': {'name': 'float32'},
  'registered_name': None},
 'layers': [{'module': 'keras.layers',
   'class_name': 'InputLayer',
   'config': {'batch_shape': (None, 2),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'input_layer',
    'optional': False},
   'registered_name': None},
  {'module': 'keras.layers',
   'class_name': 'Dense',
   'config': {'name': 'layer_1',
    'trainable': True,
    'dtype': {'module': 'keras',
     'class_name': 'DTypePolicy',
     'config': {'name': 'float32'},
     'registered_name': None},
    'units': 20,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'module': 'keras.initializers',
     'class_name': 'GlorotUniform',
     'config': {'seed': None},
     'registered_name': None},
    'bias_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
     '

[array([[-0.00823021, -0.2448125 , -0.3849056 , -0.19636351, -0.4150887 ,
          0.2839557 , -0.05482864,  0.22321177,  0.35762042,  0.18076193],
        [ 0.32369   , -0.20603153,  0.3261546 , -0.02290466,  0.34606087,
          0.1591596 , -0.3388711 , -0.39947206,  0.3296364 , -0.17746481],
        [-0.2830612 , -0.27850708,  0.13399988,  0.11311424, -0.4010101 ,
          0.22435564, -0.29822785, -0.39481416,  0.38915902,  0.38019973],
        [-0.02589589, -0.04996252, -0.38706037,  0.21801776,  0.3673172 ,
          0.41445696,  0.06026709,  0.386998  , -0.20731048,  0.2209912 ],
        [-0.18718508, -0.08846447,  0.10393697,  0.42760855, -0.01695812,
          0.39030665,  0.2827164 ,  0.34321517,  0.37218726,  0.34978622],
        [ 0.423536  ,  0.1560821 ,  0.34150547, -0.14147973, -0.20818299,
         -0.05696091, -0.30356115, -0.2737174 , -0.2501228 , -0.02282971],
        [ 0.00051734, -0.03487918,  0.24587244,  0.30038345, -0.25209206,
         -0.14358738,  0.0213051

In [130]:
pred = model.predict(X_test_model)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


In [131]:
sklearn.metrics.mean_squared_error(y_test_model, pred)

0.22748490706530683

### 6. Automatic Differentiation

#### Gradients or partial derivatives are useful for training linear models and neural networks using gradient-based optimization
#### TensorFlow's tf.GradientTape records computations and computes gradients in reverse-mode differentiation.
#### Let us see how it works.

####
#### 6.1 How to use tf.GradientTape?

In [ ]:
# declare tensor for with respect to which gradient is required
x = tf.Variable(3.0)

# using tf.GradientTape context to perform computations and record them in tape
with tf.GradientTape() as tape:
    y = 3.0 * tf.math.log(x)

# compute gradients
dy_dx = tape.gradient(y, x)  # for y = log(x), dy/dx = 1/x
print(
    "Gradient dy_dx:", dy_dx
)  # alternately doing dy_dx.numpy() returns the result as a numpy array which in this case is a single value

Gradient dy_dx: tf.Tensor(1.0, shape=(), dtype=float32)


In [ ]:
# for multi-variate functions, gradients are partial derivatives
x = tf.Variable(3.0)
y = tf.Variable(4.0)

with tf.GradientTape() as tape:
    r = x**2 + y**2

dr_dx, dr_dy = tape.gradient(
    r, [x, y]
)  # the first argument is the target function and the second one is a list of variables
print("dr_dx:", dr_dx.numpy())  # ∂r/∂x = 2x
print("dr_dy:", dr_dy.numpy())  # ∂r/∂y = 2y

dr_dx: 6.0
dr_dy: 8.0


In [ ]:
# tf.GradientTape supports the Chain Rule of Differentiation as well
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x**2  # y is a function of x
    r = y**2  # r is a function of y

dr_dx = tape.gradient(
    r, x
)  # Chain rule is applied to compute dr_dx as r is a function of x through y
print("dr_dx:", dr_dx.numpy())  # dr/dx = dr/dy × dy/dx = 2y × 2x = 2(x²) × 2x = 4x³

dr_dx: 108.0


#### Note that the intermediate variable 'y' is released outside the context of tf.GradientTape. To compute gradient dr/dy, tf.GradientTape
#### needs to be persistent

In [ ]:
# Persistent tf.GradientTape
x = tf.Variable(3.0)

with tf.GradientTape(persistent=True) as tape:
    y = x**2
    r = y**2

dr_dx = tape.gradient(r, x)
dr_dy = tape.gradient(r, y)

print("dr_dx:", dr_dx.numpy())
print("dr_dy:", dr_dy.numpy())

dr_dx: 108.0
dr_dy: 18.0


####
#### 6.2 How to use tf.GradientTape for model training?

In [ ]:
# Let us see this in action in the context of Logistic Regression

# Points to note:
# 1. For logistic regression, the probabilty P(y=1|X) = 1/[1+exp{-(WX+b)}]; where W & b are weights and bias of the model
# 2. The loss function is L = -ylog[P(y=1|X)] - (1-y)log[1-P(y=1|X)] otherwise known as binary log loss.
# 3. For training the model using Stochastic Gradient Descent, we need to compute ∂L/∂W and ∂L/∂b.

# Let us see how we can compute the gradients using tf.GradientTape

In [ ]:
# declare weights and bias of the model
num_features = 10  # the model has 10 features
W = tf.Variable(
    tf.random.normal(shape=(10,))
)  # wrapping the random numbers with tf.Variable to enable gradients on W
b = tf.Variable(
    tf.random.normal(shape=(1,))
)  # wrapping the random numbers with tf.Variable to enable gradients on b

# let us initialize a training samples
num_samples = 100

# generate training samples randomly and wrap them up in tf.constant to disable gradient computation on samples
X = tf.constant(tf.random.uniform(shape=(100, 10)))
y = tf.constant(
    tf.cast(tf.greater(tf.random.uniform(shape=(100,)), 0.80), dtype=tf.float32)
)  # target must be 0 and 1

In [ ]:
# compute gradients
with tf.GradientTape() as tape:
    log_odds = tf.reduce_sum(W * X, axis=1) + b
    # tf.reduce_sum(W * X, axis=1) results in a (1, ) vector to which b is added

    probas = tf.sigmoid(log_odds)  # using sigmoid function available in TensorFlow

    loss = tf.reduce_mean(
        -y * tf.math.log(probas) - (1.0 - y) * tf.math.log(1.0 - probas)
    )

[dloss_dW, dloss_db] = tape.gradient(loss, [W, b])

print("dloss_dW:", dloss_dW.numpy())
print("dloss_db:", dloss_db.numpy())

dloss_dW: [0.3393902  0.31333876 0.28984714 0.37596196 0.33388257 0.3055682
 0.33240983 0.3137926  0.34068426 0.3184052 ]
dloss_db: [0.6390459]


####
#### 6.3 How to disable gradient computation for selected variables?

In [ ]:
# let us use an earlier example to show how to disable gradient computation
# for multi-variate functions, gradients are partial derivatives
x = tf.Variable(
    3.0, trainable=True
)  # by default, trainable=True so we did npt mention it earlier
y = tf.Variable(
    4.0, trainable=False
)  # trainable=False signals tf.GradientTape to stop tracking the variable

with tf.GradientTape() as tape:
    r = x**2 + y**2

try:
    dr_dx, dr_dy = tape.gradient(r, [x, y])
    print("dr_dx:", dr_dx.numpy())
    print(
        "dr_dy:", dr_dy.numpy()
    )  # dr_dy is None hence this line would raise an exception
except Exception as e:
    print("Error occurred during gradient computation:\n", str(e))

dr_dx: 6.0
Error occurred during gradient computation:
 'NoneType' object has no attribute 'numpy'


## Momentum Adam..etc

In [4]:
from tensorflow import keras

tf.random.normal((3, 3), mean=0, stddev=1, name="check")

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3946698 ,  0.4907863 , -1.5649521 ],
       [ 0.7280445 ,  0.7463894 ,  0.7111015 ],
       [ 0.21908137,  0.66326386, -0.3345685 ]], dtype=float32)>

In [6]:
tf.random.uniform(shape=(3, 3)).ndim

2

In [7]:
tf.zeros(shape=(3, 3)).ndim

2

In [174]:
class NaiveLayer:
    def __init__(self, inp: int, output: int, activation=None):
        self.W = tf.Variable(
            tf.random.uniform(shape=(inp, output)), dtype=float, name="weight matrix"
        )
        # print(self.W)
        self.b = tf.zeros(shape=(output, output), dtype=float, name="bias")
        # print(self.b)
        self.activation = activation

    def __call__(self, input_variable):
        # print(input_variable,np.array(input_variable))
        # assert self.W.ndim==input_variable.ndim
        self.W = tf.Variable(self.W)
        input_variable = tf.Variable(input_variable, dtype=float, name="Input")
        print(input_variable)
        X = None
        try:
            X = tf.matmul(input_variable, self.W)
            X += self.b
        except Exception as e:
            print("Error", e)

        if self.activation:
            X = self.activation(X)
        return X

    @property
    def weights(self):  # weights of a layer of model..

        return [self.W, self.b]

In [175]:
class Sequential:
    def __init__(self, number_of_layers):
        self.layers = number_of_layers

    def __call__(self, inputs):
        x = inputs
        # inputs = tf.Variable(inputs) # Initial
        for layer in self.layers:
            x = inputs(layer)  # Layer by layer
        return x

    @property
    def weights(self):
        """
        return weights of model
        """
        weights = []
        for layer in self.layers:
            weights += layer(weights)
        return weights

In [176]:
model = Sequential(
    [
        NaiveLayer(inp=28 * 28, output=512, activation=tf.nn.relu),
        NaiveLayer(inp=512, output=1),
    ]
)

In [177]:
layer1 = model.layers[0]
layer1.W

<tf.Variable 'weight matrix:0' shape=(784, 512) dtype=float32, numpy=
array([[0.686     , 0.21790409, 0.7725712 , ..., 0.9804255 , 0.3834213 ,
        0.8043027 ],
       [0.6616638 , 0.404817  , 0.31048262, ..., 0.86754405, 0.6525861 ,
        0.9482347 ],
       [0.7505748 , 0.16669703, 0.20816755, ..., 0.50057185, 0.57947254,
        0.32915545],
       ...,
       [0.6387974 , 0.89734674, 0.89997303, ..., 0.6831478 , 0.97233856,
        0.5630665 ],
       [0.6221355 , 0.74689615, 0.9922825 , ..., 0.73690116, 0.45170677,
        0.18724513],
       [0.8446975 , 0.71179926, 0.15653968, ..., 0.33184707, 0.62245   ,
        0.00568986]], shape=(784, 512), dtype=float32)>

In [178]:
layer = model.layers[0]

In [179]:
W, b = model.layers[0].weights

In [180]:
model.weights

<tf.Variable 'Input:0' shape=(0,) dtype=float32, numpy=array([], dtype=float32)>
Error {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} In[0] and In[1] has different ndims: [0] vs. [784,512] [Op:MatMul] name: 


ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

In [168]:
a = [layer.weights for layer in model.layers]

In [169]:
W1, b1 = model.layers[1].weights

In [170]:
W1.name

'weight matrix:0'

In [171]:
type(b1)

tensorflow.python.framework.ops.EagerTensor

In [172]:
tf.random.uniform(shape=(28 * 28, 512)).ndim

2

In [173]:
tf.zeros(
    512,
).ndim

1

In [185]:
x = tf.constant(
    [
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
    ],
    dtype=tf.float32,
)
y = tf.Variable([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14]])

In [186]:
x.ndim

2

In [162]:
tf.linalg.matmul(x, y).numpy()

array([[ 90, 100, 110],
       [240, 275, 310],
       [390, 450, 510],
       [540, 625, 710],
       [690, 800, 910]], dtype=int32)

In [205]:
x = tf.Variable(3.0)
x.numpy()

np.float32(3.0)

In [206]:
x.dtype

tf.float32

In [207]:
with tf.GradientTape() as tape:
    y = 2 * tf.math.log(x)
dy_dx = tape.gradient(y, x)
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=0.6666666865348816>

## Part 3 Mnist

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()
model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy())