In [1]:
import numpy as np
import torch

In [2]:
class Linear(torch.nn.Module):
    def __init__(self, inp, out):
        super(Linear, self).__init__()
        self.W = torch.randn(inp, out)
        self.bias = torch.zeros(out)

    def forward(self, x):
        return x @ self.W.T + self.bias

In [28]:
linear = Linear(2, 2)

In [29]:
print(linear)

Linear()


In [30]:
x_input = torch.tensor([[1, 2.0]])
y_hat = linear(x_input)

In [31]:
y_hat

tensor([[-1.1262, -1.6996]])

In [32]:
print(y_hat)

tensor([[-1.1262, -1.6996]])


In [33]:
print(linear.W)

tensor([[ 0.6116, -0.8689],
        [-0.3186, -0.6905]])


In [34]:
linear_nn = torch.nn.Linear(2, 2)

In [35]:
y_check = linear_nn(x_input)

In [36]:
linear_nn.weight

Parameter containing:
tensor([[-0.3223,  0.0633],
        [ 0.2224, -0.1852]], requires_grad=True)

In [37]:
linear_nn.bias

Parameter containing:
tensor([ 0.2020, -0.1689], requires_grad=True)

In [38]:
with torch.no_grad():
    linear_nn.bias[:] = 0

In [39]:
linear_nn.bias

Parameter containing:
tensor([0., 0.], requires_grad=True)

In [20]:
y_check1 = linear_nn(x_input)

In [21]:
print(y_check1)

tensor([[ 1.1371, -0.7502]], grad_fn=<AddmmBackward0>)


In [22]:
print(y_hat)

tensor([[ 0.6665, -1.0049]])


In [23]:
linear_nn.weight

Parameter containing:
tensor([[ 0.3475,  0.3948],
        [-0.1479, -0.3012]], requires_grad=True)