In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.array(
    [
        ["A", "B", "C"],
        ["B", "C", "A"],
        ["C", "A", "B"],
        ["A", "C", "B"],
        ["A", "A", "B"],
    ]
)

In [3]:
data

array([['A', 'B', 'C'],
       ['B', 'C', 'A'],
       ['C', 'A', 'B'],
       ['A', 'C', 'B'],
       ['A', 'A', 'B']], dtype='<U1')

(5, 3)

In [17]:
np.random.seed(4)
k = 2
modes = data[np.random.choice(data.shape[0], k, replace=False)]

In [18]:
modes

array([['A', 'B', 'C'],
       ['A', 'C', 'B']], dtype='<U1')

In [26]:
clusters = np.zeros(data.shape[0], dtype=int)

In [27]:
clusters

array([0, 0, 0, 0, 0])

In [1]:
import torch

mps_device = torch.device("mps")

In [29]:
x = torch.ones(5, device=mps_device)

In [30]:
x

tensor([1., 1., 1., 1., 1.], device='mps:0')

In [31]:
x.T

/var/folders/_c/vv6vtlfj21df0q59qf7zxzgr0000gn/T/ipykernel_65112/2120005694.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:4416.)
  x.T


tensor([1., 1., 1., 1., 1.], device='mps:0')

In [2]:
w = torch.empty(3, 5)

In [3]:
w.to(device=mps_device)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='mps:0')

9