In [1]:
import math
result = math.ceil(4.2)
print(result)

5


In [2]:
math.floor(4.9)

4

In [3]:
round(4.9)

5

In [4]:
round(4.2)

4

In [5]:
round(4.5)

4

In [6]:
round(4.51)

5

In [11]:
class Student:
    def __init__(self,name,age):
        self._name = name
        self._age = age
        self._grade = []
    def add_grade(self,grade):
        self._grade.append(grade)

    def average_grade(self):
        if len(self._grade):
            return sum(self._grade)/len(self._grade)
        else:
            return 0

In [12]:
s = Student("Deven",24)

print(s.average_grade())

0


In [13]:
s.add_grade(10);s.add_grade(5)

In [148]:
from operator import itemgetter
class Dataset:
    def __init__(self,data):
        self.data = data
    def mean(self):
        return sum(self.data)/len(self.data)
    def median(self):
        sorted_data = sorted(self.data)
        middle = len(sorted_data)//2
        if middle%2==0:
            return sorted_data[middle-1]
        else:
            return sorted_data[middle]

    def mode(self):
        mapping = dict()
        for x in self.data:
            if x in mapping:
                mapping[x]+=1
            else:
                mapping[x]=1
        m=sorted(mapping.items(),key=itemgetter(1),reverse=True)
        print(m)

        return m[0][0]

    def std_dev(self):
        #mean_value = sum(self.data) / len(self.data)
        return (sum((x - self.mean()) ** 2 for x in self.data) / len(self.data)) ** 0.5
    def detect_outliers(self, threshold=2):

        return [x for x in self.data if(abs(self.mean()-x)>self.std_dev()*threshold)]

In [108]:
math.exp(2)

7.38905609893065

In [109]:
math.log(8,2)

3.0

In [110]:
math.log(10,10)

1.0

In [111]:
val = math.e**2
math.log(val)

2.0

In [112]:
import random
print(random.random())

0.8235888725334455


In [113]:
val = random.randint(1,10)

In [114]:
val

3

In [115]:
uniform = random.uniform(1,5)

In [116]:
uniform

1.1376142955025839

In [117]:
import numpy as np

In [118]:
lst = np.arange(1,5,dtype=int)

In [119]:
lst

array([1, 2, 3, 4])

In [120]:
random.shuffle(lst)

In [121]:
lst

array([3, 1, 2, 4])

In [122]:
random.seed(10)

In [123]:
random.shuffle(lst)
lst

array([4, 2, 1, 3])

In [124]:
random.choice(lst)

np.int64(4)

In [125]:
my_list = list(range(1,11))

In [126]:
random.sample(my_list,3)

[4, 8, 9]

In [149]:
data = Dataset([5,5,10,15,20,25,100])
print(data.detect_outliers(0.4))

[5, 5, 10, 100]


In [150]:
data.mode()

[(5, 2), (10, 1), (15, 1), (20, 1), (25, 1), (100, 1)]


5

In [99]:
d=dict({10:2,100:3})

In [106]:
sorted(d.items(),key=itemgetter(1),reverse=True).pop()[0]

10

In [151]:
nums=[1,2,3,4]
random.choice(nums)

3

In [152]:
import datetime
curr = datetime.datetime.now()

In [153]:
curr

datetime.datetime(2024, 12, 7, 23, 55, 51, 842473)

In [154]:
type(curr)

datetime.datetime

In [155]:
from math import pi
class Circle:
    def __init__(self, radius):
        self.radius = radius
    def calculate_area(self):
        return pi * self.radius * self.radius
circle1 = Circle(6)
area = circle1.calculate_area()

In [156]:
print(area)

113.09733552923255


In [172]:
def utility(s):
    # Your code here
    for i in range(0,len(s),2):
        print(s[i],end='')
    #return s[0:len(s):2]


In [173]:
s = "DoctorPhenomenal"
utility(s)

DcoPeoea

In [174]:
file = 'temp.txt'
with open(file,'w+') as f:
    f.write("Deven is a good boy")


In [175]:
with open(file,'a+') as f:
    f.write("He is stupid")

In [176]:
with open(file,'r+') as f:
    print(f.read())

Deven is a good boy
He is stupid


In [178]:
file1 = open("myfile.txt","w")
L = ["This is Delhi \n","This is Paris \n","This is London \n"]
file1.write(''.join(L))
file1.close()

In [179]:
file1 = open('myfile.txt','a')
file1.writelines(L)
file1.close()

In [180]:

file1 = open("myfile.txt","r+")

print("Output of Read function is ")
print(file1.read())
print()


Output of Read function is 
This is Delhi 
This is Paris 
This is London 
This is Delhi 
This is Paris 
This is London 




In [181]:

# seek(n) takes the file handle to the nth
# bite from the beginning.
file1.seek(0)

print( "Output of Readline function is ")
print(file1.readline())
print()


Output of Readline function is 
This is Delhi 




In [182]:
file1.seek(0)
print(file1.readlines())

['This is Delhi \n', 'This is Paris \n', 'This is London \n', 'This is Delhi \n', 'This is Paris \n', 'This is London \n']


In [183]:
file1.seek(9)
print(file1.read())

elhi 
This is Paris 
This is London 
This is Delhi 
This is Paris 
This is London 



In [184]:
file1.close()

In [185]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


2024-12-08 00:52:12.853 Python[37624:862449] +[IMKClient subclass]: chose IMKClient_Modern


True

In [209]:
txt = "Hello Geeks. We're hoping you guys are doing great."

In [210]:
len(txt.split("."))

3

In [211]:
len(txt.split())

9

In [212]:
len(txt.split(' '))

9

In [213]:
txt1 = "Hello Geeks. We're hoping you guys are doing great."
len(txt1.split("."))

3

In [214]:
txt1.split(".")

['Hello Geeks', " We're hoping you guys are doing great", '']

In [215]:
txt.split(".")

['Hello Geeks', " We're hoping you guys are doing great", '']

In [216]:
txt1.split()

['Hello', 'Geeks.', "We're", 'hoping', 'you', 'guys', 'are', 'doing', 'great.']

In [217]:
len(txt1.split(' '))

9

In [218]:
len(txt.split())

9

In [219]:
txt==txt1

True

In [222]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [223]:
word_tokenize(txt)

['Hello',
 'Geeks',
 '.',
 'We',
 "'re",
 'hoping',
 'you',
 'guys',
 'are',
 'doing',
 'great',
 '.']

In [225]:
sentences=sent_tokenize(txt)

In [226]:
sentences

['Hello Geeks.', "We're hoping you guys are doing great."]

In [227]:
words = word_tokenize(txt)

In [228]:
len(words)

12

In [229]:
for w in words:
    print(w,end=' ')

Hello Geeks . We 're hoping you guys are doing great . 