In [1]:
import numpy as np
import torch
import torch.nn.functional as F

In [2]:
from torch import nn

In [3]:
x = nn.Linear(in_features=4, out_features=4)

In [4]:
a = torch.tensor([[1.0, 2, 3, 4]] * 3)

In [5]:
import copy

b = copy.deepcopy(a)
b += 1

In [6]:
b = torch.tensor([[1.0, 2, 3, 4]] * 4)

In [7]:
b

tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])

In [8]:
model = copy.deepcopy(x)

In [9]:
out = model(a)

In [10]:
pred = model(b)

In [11]:
pred

tensor([[ 0.6600,  1.9459, -1.2793,  0.1180],
        [ 0.6600,  1.9459, -1.2793,  0.1180],
        [ 0.6600,  1.9459, -1.2793,  0.1180],
        [ 0.6600,  1.9459, -1.2793,  0.1180]], grad_fn=<AddmmBackward0>)

In [12]:
print(pred)

tensor([[ 0.6600,  1.9459, -1.2793,  0.1180],
        [ 0.6600,  1.9459, -1.2793,  0.1180],
        [ 0.6600,  1.9459, -1.2793,  0.1180],
        [ 0.6600,  1.9459, -1.2793,  0.1180]], grad_fn=<AddmmBackward0>)


In [13]:
input_tensor = torch.randn(10, 3)
input_tensor

tensor([[ 0.2591,  1.8726,  1.4723],
        [ 1.4820, -0.9166, -1.3362],
        [ 0.2463,  0.5125, -1.6677],
        [ 0.5681, -0.3155,  1.2822],
        [-0.1929,  0.7444, -0.4235],
        [ 0.3358,  0.3425,  0.3689],
        [-0.0245,  1.6349, -0.7055],
        [ 0.6273,  0.6979,  0.4437],
        [ 0.4162, -1.7148, -0.2185],
        [-1.0587, -0.2603,  0.1786]])

In [14]:
weight_tensor = torch.randn(5, 3, requires_grad=True)

In [15]:
bias = torch.randn(5, requires_grad=True)

In [16]:
output_functional = F.linear(input_tensor, weight_tensor, bias)

In [17]:
output_functional

tensor([[-0.8791,  3.1788,  1.4443, -3.3971,  0.5817],
        [-1.1624, -0.3441,  3.6399,  2.8992, -4.5205],
        [-1.5564, -1.6207,  2.7984,  1.0545, -3.9942],
        [ 0.4612,  2.9398,  2.2624, -0.4988,  0.0713],
        [-0.7406, -0.0684,  2.1570, -0.4976, -1.8075],
        [-0.3748,  1.4643,  2.2560, -0.5451, -1.0816],
        [-1.6909, -0.2919,  2.0627, -1.2504, -2.3714],
        [-0.8101,  1.8178,  2.2577, -0.9357, -1.2189],
        [ 0.8101,  0.4777,  3.0605,  2.4745, -1.9854],
        [ 0.9649,  0.1139,  1.8828, -0.1406, -0.1925]],
       grad_fn=<AddmmBackward0>)

In [18]:
print(output_functional)

tensor([[-0.8791,  3.1788,  1.4443, -3.3971,  0.5817],
        [-1.1624, -0.3441,  3.6399,  2.8992, -4.5205],
        [-1.5564, -1.6207,  2.7984,  1.0545, -3.9942],
        [ 0.4612,  2.9398,  2.2624, -0.4988,  0.0713],
        [-0.7406, -0.0684,  2.1570, -0.4976, -1.8075],
        [-0.3748,  1.4643,  2.2560, -0.5451, -1.0816],
        [-1.6909, -0.2919,  2.0627, -1.2504, -2.3714],
        [-0.8101,  1.8178,  2.2577, -0.9357, -1.2189],
        [ 0.8101,  0.4777,  3.0605,  2.4745, -1.9854],
        [ 0.9649,  0.1139,  1.8828, -0.1406, -0.1925]],
       grad_fn=<AddmmBackward0>)


In [19]:
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        # Stateful layers: They manage their own weights and biases internally

        self.fc1 = nn.Linear(in_features=10, out_features=5)
        self.fc2 = nn.Linear(5, 2)

    def forward(self, x):
        # Stateless activation: F.relu does not have weights

        x = F.relu(self.fc1(x))

        # Stateless output activation: Softmax over the last dimension
        x = F.softmax(self.fc2(x), dim=-1)
        return x

    def __call__(self, x, *args, **kwargs):
        return self.forward(x)

In [20]:
net = SimpleNet()

In [21]:
dummy = torch.randn(1, 10)
out = net(dummy)

In [22]:
dummy.shape

torch.Size([1, 10])

In [23]:
out.shape

torch.Size([1, 2])

In [24]:
x, b = list(net.fc1.parameters())

In [25]:
b

Parameter containing:
tensor([-0.1921, -0.0427,  0.1018,  0.0317,  0.2158], requires_grad=True)

In [26]:
import torch.functional as F1

x = F1.Tensor([1, 2, 3])

In [27]:
x.shape

torch.Size([3])

In [28]:
x.device

device(type='cpu')

In [30]:
device = "mps" if torch.mps.is_available() else "cpu"

In [31]:
device

'mps'

In [32]:
x.to(device)

tensor([1., 2., 3.], device='mps:0')

In [33]:
torch.rand(10, 3).to(device)

tensor([[0.1775, 0.3503, 0.4822],
        [0.4862, 0.4246, 0.3788],
        [0.6830, 0.2933, 0.0206],
        [0.5171, 0.8442, 0.1225],
        [0.9679, 0.5467, 0.1280],
        [0.2582, 0.1728, 0.5581],
        [0.9994, 0.9317, 0.6336],
        [0.0360, 0.1188, 0.9248],
        [0.9148, 0.6057, 0.2976],
        [0.6608, 0.5452, 0.1029]], device='mps:0')

In [34]:
torch.__version__

'2.13.0'

ModuleNotFoundError: No module named 'torchrun'