In [2]:
"""

"""

import numpy as np

np.arange(1, 3)

array([1, 2])

In [3]:
a = np.array([1, 2, 3]).reshape(3, 1)

In [4]:
a

array([[1],
       [2],
       [3]])

In [5]:
a.reshape((1, 3))

array([[1, 2, 3]])