In [1]:
import torch

In [2]:
x = torch.tensor([1, 0.1])

In [3]:
W = torch.tensor([[1, 0.2], [-3, 1]])

In [24]:
x1 = x @ W

In [47]:
x1

tensor([0.7000, 0.3000])

In [25]:
x2 = torch.tanh(x1)

In [55]:
x2

tensor([0.6044, 0.2913])

In [43]:
W1 = torch.tensor([[1.0], [-1.0]])

In [32]:
x3 = x2 @ W1

In [33]:
lr = -0.2

In [35]:
y = 0.5
L = 0.5 * (x2 - y) ** 2

In [36]:
L

tensor([0.0054, 0.0218])

In [40]:
dl_dx3 = x3 - y

In [44]:
dl_dlx2 = dl_dx3 * W1

In [46]:
print(dl_dlx2)

tensor([[-0.1869],
        [ 0.1869]])


In [72]:
temp = torch.tanh(x1[0])
temp = 1 - temp * temp
temp1 = 1 - (torch.tanh(x1[1]) * torch.tanh(x1[1]))

In [73]:
temp1

tensor(0.9151)

In [76]:
dl_dlx1 = dl_dlx2 * (torch.tensor([[temp, 0], [0, temp1]]))

In [77]:
print(dl_dlx1)

tensor([[-0.1187, -0.0000],
        [ 0.0000,  0.1711]])


In [66]:
temp1

tensor(0.9901)

In [67]:
0.1869 * 0.9901

0.18504969000000002