In [1]:
import numpy as np

In [10]:
(1 / 1 - np.log(0.63))

np.float64(1.4620354595965588)

In [11]:
np.e

2.718281828459045

In [12]:
z = 0.63

In [15]:
import math
import numpy as np

sigmoid = lambda x: 1 / (1 + np.exp(-x))

In [17]:
print(sigmoid(1))

0.7310585786300049


In [18]:
math.exp(1)

2.718281828459045

In [19]:
bias = np.array([0.1, 0.25])

In [20]:
bias.T

array([0.1 , 0.25])

In [21]:
X = np.array([1.61, 1.8])
W = np.array([0.2, 0.5])
z1 = W @ X + bias
z1

array([1.322, 1.472])

In [22]:
1 / (1 + np.e ** (-z1))

array([0.78951426, 0.81336119])

In [23]:
-z1

array([-1.322, -1.472])

In [24]:
W = np.array([[3, 4], [1, 9], [6, 2]])
X = np.array([1, 2])
h1 = W @ X
h1

array([11, 19, 10])

In [25]:
from keras.src.activations import softmax

help(softmax)

Help on function softmax in module keras.src.activations.activations:

softmax(x, axis=-1)
    Softmax converts a vector of values to a probability distribution.

    The elements of the output vector are in range `[0, 1]` and sum to 1.

    Each input vector is handled independently.
    The `axis` argument sets which axis of the input the function
    is applied along.

    Softmax is often used as the activation for the last
    layer of a classification network because the result could be interpreted as
    a probability distribution.

    The softmax of each vector x is computed as
    `exp(x) / sum(exp(x))`.

    The input values in are the log-odds of the resulting probability.

    Args:
        x: Input tensor.
        axis: Integer, axis along which the softmax is applied.



In [26]:
a = np.e ** (h1)

In [27]:
print(f"{()}")

()


In [28]:
out = a / np.sum(a)
out

array([3.35308764e-04, 9.99541338e-01, 1.23353201e-04])

In [29]:
print(f"{out:.4d}")

TypeError: unsupported format string passed to numpy.ndarray.__format__

In [30]:
3 - 0.3 * (8)

0.6000000000000001

In [31]:
0.6 - 2.4

-1.7999999999999998

In [36]:
import tensorflow as tf

# todo
# def calculating_loss(X,alpha,epochs):
#    step = X

In [33]:
0.6 - 0.3 * (2 * 0.6 + 2)

-0.36

In [34]:
-0.36 - 3 * (2 * 0.36 + 2)

-8.52

In [35]:
%%time
a = np.array([[1, 2], [3, 4]] * 5)
print(a)

[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]
CPU times: user 184 μs, sys: 15 μs, total: 199 μs
Wall time: 195 μs


In [37]:
%%time
b = tf.constant([[1, 2], [3, 4]] * 5)
print(b)

tf.Tensor(
[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]], shape=(10, 2), dtype=int32)
CPU times: user 4.26 ms, sys: 12.8 ms, total: 17 ms
Wall time: 42.9 ms


In [39]:
print(tf.device)

<function device_v2 at 0x13f82afc0>


In [40]:
b.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [41]:
str(b)

'tf.Tensor(\n[[1 2]\n [3 4]\n [1 2]\n [3 4]\n [1 2]\n [3 4]\n [1 2]\n [3 4]\n [1 2]\n [3 4]], shape=(10, 2), dtype=int32)'

In [42]:
dir(b)

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__complex__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclass

In [43]:
b.ndim

2

In [44]:
b.shape

TensorShape([10, 2])

In [53]:
b.set_shape((10, 2))

In [54]:
c = np.random.randn(2, 2, 2, 2)
c

array([[[[ 2.80116838,  0.66720085],
         [ 1.46855827, -0.0819483 ]],

        [[-0.77252648,  0.14181055],
         [ 1.30375436, -0.04905299]]],


       [[[-0.07907532,  0.1102445 ],
         [ 1.57528823,  1.51012727]],

        [[-1.63881422, -0.81625744],
         [ 0.67806332, -0.423968  ]]]])

In [55]:
c.shape

(2, 2, 2, 2)

In [57]:
c.reshape(-1)

array([ 2.80116838,  0.66720085,  1.46855827, -0.0819483 , -0.77252648,
        0.14181055,  1.30375436, -0.04905299, -0.07907532,  0.1102445 ,
        1.57528823,  1.51012727, -1.63881422, -0.81625744,  0.67806332,
       -0.423968  ])