In [2]:
import keras
import numpy as np
import pandas as pd

import tensorflow as tf

In [2]:
W0 = np.array([[3, 4], [1, 9], [6, 2]])
h2 = np.array([1, 2])

In [3]:
h2

array([1, 2])

In [4]:
W0

array([[3, 4],
       [1, 9],
       [6, 2]])

In [5]:
W0 @ h2

array([11, 19, 10])

In [6]:
df = pd.read_csv("sample30.csv")

In [7]:
df.isna().sum()

id                          0
brand                       0
categories                  0
manufacturer              141
name                        0
reviews_date               46
reviews_didPurchase     14068
reviews_doRecommend      2570
reviews_rating              0
reviews_text                0
reviews_title             190
reviews_userCity        28071
reviews_userProvince    29830
reviews_username           63
user_sentiment              1
dtype: int64

In [8]:
?df.dropna()

Object `df.dropna()` not found.


In [3]:
x = np.array([[200, 17], [120.0, 5.0], [425.0, 20.0], [212.0, 8.0]], dtype=float)

In [4]:
layer_0 = tf.keras.Input(shape=(x.shape[0],))
layer_1 = tf.keras.layers.Dense(
    units=3,
    activation=tf.keras.activations.sigmoid,
    name="first_layer",
    input_dim=tf.keras.Input(shape=(x.shape[0],)),
)(layer_0)

/Users/ankster/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [43]:
a0 = tf.keras.Model(layer_0, layer_1)

In [44]:
a0.get_weights()

[array([[ 0.04276961, -0.04968828, -0.84638304],
        [-0.16289103,  0.12981558, -0.21934563],
        [ 0.86481977,  0.53724515,  0.28596807],
        [-0.8304523 , -0.22078192,  0.306733  ]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [45]:
layer_2 = tf.keras.layers.Dense(
    units=1, activation=tf.keras.activations.sigmoid, name="output_layer"
)

In [46]:
a2 = layer_2(a1)

In [47]:
layer_2.get_weights()

[array([[-0.6461752 ],
        [-0.91445434],
        [-1.1385754 ]], dtype=float32),
 array([0.], dtype=float32)]

In [50]:
print(a2.numpy())

[[0.17355631]
 [0.17355631]
 [0.17355631]
 [0.17355631]]


In [27]:
out.numpy()

array([[0.46366426],
       [0.49276936],
       [0.46297035],
       [0.47904375]], dtype=float32)

## Simply

In [51]:
x = np.array([[200, 17], [120.0, 5.0], [425.0, 20.0], [212.0, 8.0]], dtype=float)

In [120]:
x.shape[-1]

2

In [142]:
layer_0 = tf.keras.Input(shape=(2,))
layer_1 = tf.keras.layers.Dense(
    units=3, activation=tf.keras.activations.sigmoid, name="input_layer"
)

In [143]:
layer_2 = tf.keras.layers.Dense(
    units=1, activation=tf.keras.activations.sigmoid, name="output_layer"
)

In [144]:
model = tf.keras.Sequential()
model.add(layer_0)
model.add(layer_1)
model.add(layer_2)

In [145]:
y = np.array([1, 0, 0, 1])

In [146]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.03),
    loss=tf.keras.losses.binary_crossentropy,
    metrics=["accuracy"],
)

In [147]:
model.get_weights()

[array([[ 0.7371224 ,  0.609967  , -0.97907627],
        [ 0.3607564 ,  0.8462806 ,  0.5164989 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[-0.9633827 ],
        [ 0.45592952],
        [ 0.83913004]], dtype=float32),
 array([0.], dtype=float32)]

In [153]:
predictions = model.fit(x, y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5000 - loss: 0.6962


In [155]:
dir(predictions)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_api_export_path',
 '_api_export_symbol_id',
 '_model',
 'epoch',
 'history',
 'model',
 'on_batch_begin',
 'on_batch_end',
 'on_epoch_begin',
 'on_epoch_end',
 'on_predict_batch_begin',
 'on_predict_batch_end',
 'on_predict_begin',
 'on_predict_end',
 'on_test_batch_begin',
 'on_test_batch_end',
 'on_test_begin',
 'on_test_end',
 'on_train_batch_begin',
 'on_train_batch_end',
 'on_train_begin',
 'on_train_end',
 'params',
 'set_model',
 'set_params']

There are many categories of matrices: Symmetric, Orthogonal, Singular, Invertible, Square, Diagonalizable, and more. This is a
map of the categories using a venn diagram. From the top to the bottom, I'm walking you through this diagram. All matrices (𝑚×𝑛) can
be factorized to 𝑨 = 𝑪𝑹 and also be factorized into 𝑨 = 𝑼𝜮𝑽𝐓
.
Square matrices (𝑛×𝑛) are either Invertible or Singular. Invertibility, indicated by the dotted line through the center, can be checked by
whether 𝑨 = 𝑳𝑼 has full pivots, det (𝑨) ≠ 𝟎 or all eigenvalues are nonzero.
An Invertible matrix is factorized into 𝑨 = 𝑸𝑹 using Orthogonal matrix 𝑸 (Gram-Schmidt). A Square matrix is either Diagonalizable
if it has 𝑛 independent eigenvectors.
A Diagonalizable matrix is factorized into 𝑨 = 𝑿𝚲𝑿"𝟏 with a Diagonal eigenvalue matrix 𝚲 and an Invertible eigenvector matrix 𝑿. A
Non-diagonalizable matrix has its Jordan normal form 𝑱 instead of the diagonal matrix 𝚲.
There is an important category Normal which includes Symmetric, Orthogonal, Anti-Symmetric matrices. A matrix is Diagonalizable
as 𝑸𝚲𝑸"𝟏 by an Orthogonal matrix 𝑸 when and only when it is Normal (𝑨𝐓𝑨 = 𝑨𝑨𝐓 ).
Symmetric matrices (𝑺 = 𝑺𝐓) and Orthogonal matrices (𝑸"𝟏 = 𝑸𝐓) are important Normal matrices. Some matrices are both
Symmetric and Orthogonal. They include reflection matrices with eigenvalues 1 and -1.
All eigenvalues of an Orthogonal matrix have |𝜆| = 1. All eigenvalues of a Symmetric matrix are real. A Symmetric matrix is called
Positive Semidefinite if all eigenvalues 𝜆 ≥ 0, and Positive Definite if all eigenvalues 𝜆 > 0.
Projection matrices (𝑷𝟐 = 𝑷 = 𝑷𝐓) are Symmetric and Positive Semidefinite, with all the eigenvalues are 1 or 0.
The Identity is the only Invertible Projection matrix.

In [157]:
predictions.history

{'accuracy': [0.5], 'loss': [0.6962015628814697]}