In [ ]:
import numpy as np
import tensorflow as tf

In [2]:
x = tf.random.normal(shape=(3, 1), mean=0.0, stddev=1.0)

In [3]:
print(x)

tf.Tensor(
[[-1.3005686]
 [-0.7940285]
 [-1.759279 ]], shape=(3, 1), dtype=float32)


In [4]:
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[-1.3005686],
       [-0.7940285],
       [-1.759279 ]], dtype=float32)>

In [6]:
np.mean(x)

np.float32(-1.2846254)

In [7]:
np.std(x)

np.float32(0.3942231)

In [8]:
v = tf.Variable(initial_value=x)

In [9]:
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.3005686],
       [-0.7940285],
       [-1.759279 ]], dtype=float32)>

In [10]:
v[0, 0].assign(3)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[ 3.       ],
       [-0.7940285],
       [-1.759279 ]], dtype=float32)>

In [11]:
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 3.       ],
       [-0.7940285],
       [-1.759279 ]], dtype=float32)>

In [13]:
v.assign_add(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[ 4.        ],
       [ 0.20597148],
       [-0.759279  ]], dtype=float32)>

In [14]:
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 4.        ],
       [ 0.20597148],
       [-0.759279  ]], dtype=float32)>

In [15]:
a = t
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [26]:
b = tf.zeros(shape=2)

In [33]:
c = tf.square(a)
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [31]:
tf.concat((a, c), axis=0)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [32]:
tf.matmul(a, c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [35]:
a + c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [36]:
a @ c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [37]:
tf.multiply(a, c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [38]:
np.multiply(a, c)

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [39]:
np.matmul(a, c)

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [40]:
def dense(inp, weight, bias):
    return tf.nn.relu(tf.matmul(inp, weight) + bias)

In [41]:
a.ndim

2

In [42]:
a.shape

TensorShape([2, 2])