# Cheatsheet

## Layers

In [1]:
from typing import Any

import torch
import torch.nn as nn

# 1. Define the dimensions
BATCH_SIZE = 10
SEQ_LEN = 100
INPUT_DIM = 64
OUTPUT_DIM = 32

# 2. Instantiate the linear layer
# It expects the incoming features to be 64, and transforms them into 32
linear_layer = nn.Sequential(
    nn.Linear(in_features=INPUT_DIM, out_features=1),
    nn.Linear(in_features=1, out_features=OUTPUT_DIM),
)

# 3. Create a 3D input tensor matching your Transformer data layout
# Shape: (Batch Size, Sequence Length, Features)
x = torch.randn(BATCH_SIZE, SEQ_LEN, INPUT_DIM)
print(f"Input shape:  {x.shape=}")  # Output: torch.Size([10, 100, 64])

# 4. Pass the tensor through the layer
output = linear_layer(x)
print(f"Output shape: {output.shape=}")  # Output: torch.Size([10, 100, 32])

Input shape:  x.shape=torch.Size([10, 100, 64])
Output shape: output.shape=torch.Size([10, 100, 32])


In [2]:
test_1 = nn.Linear(in_features=INPUT_DIM, out_features=1)
test_1(x).shape

torch.Size([10, 100, 1])

In [3]:
# adding relu
test_2 = nn.Sequential(
    nn.Linear(in_features=INPUT_DIM, out_features=1),
    nn.ReLU(),
)
out = test_2(x)
print(f"{out.shape=}")

out.shape=torch.Size([10, 100, 1])


In [4]:
out.requires_grad, output.requires_grad

(True, True)

In [5]:
x = torch.tensor([[2.0, 3], [3, 2]])
x

tensor([[2., 3.],
        [3., 2.]])

In [6]:
inp = torch.randn(10, 100, 64)

In [7]:
attention_mask = torch.tensor([[0, 1.0], [1.0, 0]])

In [8]:
x.shape

torch.Size([2, 2])

In [9]:
# import copy
# attention_mask = copy.deepcopy(x)

In [10]:
# model(inp,attn_mask=None)

## Operations cat stack squeeze

In [11]:
attention_mask.unsqueeze(0).shape, attention_mask.shape

(torch.Size([1, 2, 2]), torch.Size([2, 2]))

In [12]:
attention_mask.view(1, attention_mask.shape[-2], attention_mask.shape[-1]).shape

torch.Size([1, 2, 2])

In [13]:
x

tensor([[2., 3.],
        [3., 2.]])

In [14]:
torch.cat([x, x], dim=-1)

tensor([[2., 3., 2., 3.],
        [3., 2., 3., 2.]])

In [15]:
torch.cat([x, x], dim=1)

tensor([[2., 3., 2., 3.],
        [3., 2., 3., 2.]])

In [16]:
assert (torch.cat([x, x], dim=-1) == torch.cat([x, x], dim=1)).all()

In [17]:
torch.cat([x, x], dim=0)

tensor([[2., 3.],
        [3., 2.],
        [2., 3.],
        [3., 2.]])

In [18]:
torch.stack([x, x], dim=0)

tensor([[[2., 3.],
         [3., 2.]],

        [[2., 3.],
         [3., 2.]]])

In [19]:
torch.stack([x, x], dim=1)

tensor([[[2., 3.],
         [2., 3.]],

        [[3., 2.],
         [3., 2.]]])

In [20]:
torch.stack([x, x], dim=2)

tensor([[[2., 2.],
         [3., 3.]],

        [[3., 3.],
         [2., 2.]]])

In [22]:
# torch.stack([x,x],dim=3)

## Direct Calculation

In [23]:
torch.softmax(x, dim=0)

tensor([[0.2689, 0.7311],
        [0.7311, 0.2689]])

In [24]:
torch.softmax(x, dim=1)

tensor([[0.2689, 0.7311],
        [0.7311, 0.2689]])

In [25]:
x = torch.randn(3, 32, 32)
n = len(x) - 1
print(x[0, :, 1])

tensor([ 0.4984, -0.2751,  0.4641,  0.7892,  0.3241, -1.4274,  0.5133,  1.9153,
         0.7065,  0.5089, -1.4710,  2.0903, -0.2608, -0.3189, -0.3841, -1.0213,
         0.1658,  0.9755, -0.8450, -0.0031,  0.0920,  0.2556,  0.3953,  0.6242,
         0.1475, -1.0089, -0.6101,  0.1354, -2.2926, -0.2651,  0.1431, -0.5212])


In [26]:
x1 = torch.randn(32, 32)

In [27]:
x1.softmax(dim=0)

tensor([[0.0076, 0.0061, 0.0572,  ..., 0.0319, 0.0274, 0.0441],
        [0.0096, 0.0098, 0.0242,  ..., 0.0451, 0.0111, 0.0204],
        [0.0036, 0.0141, 0.0552,  ..., 0.0078, 0.0088, 0.0263],
        ...,
        [0.0746, 0.0067, 0.0097,  ..., 0.0100, 0.0457, 0.0193],
        [0.0153, 0.0323, 0.0255,  ..., 0.0486, 0.0368, 0.0688],
        [0.0748, 0.0188, 0.0135,  ..., 0.0223, 0.0064, 0.0037]])

In [28]:
x1.softmax(dim=1)

tensor([[0.0132, 0.0105, 0.0970,  ..., 0.0247, 0.0414, 0.0534],
        [0.0100, 0.0101, 0.0246,  ..., 0.0209, 0.0100, 0.0148],
        [0.0044, 0.0167, 0.0646,  ..., 0.0042, 0.0092, 0.0220],
        ...,
        [0.0816, 0.0072, 0.0102,  ..., 0.0048, 0.0432, 0.0146],
        [0.0202, 0.0420, 0.0327,  ..., 0.0284, 0.0420, 0.0630],
        [0.0954, 0.0235, 0.0167,  ..., 0.0125, 0.0071, 0.0032]])

In [29]:
torch.tensor([1.0]).softmax(dim=0)

tensor([1.])

In [30]:
torch.tensor([1.0]).relu()

tensor([1.])

In [31]:
x.relu_()

tensor([[[2.0981, 0.4984, 0.1248,  ..., 0.7762, 1.4056, 0.0000],
         [0.7291, 0.0000, 0.6834,  ..., 0.0000, 0.0000, 0.9463],
         [0.3137, 0.4641, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 2.5350, 0.0236, 1.4803],
         [1.1855, 0.1431, 1.3255,  ..., 0.0000, 0.5620, 1.5636],
         [0.7161, 0.0000, 0.6960,  ..., 0.9799, 1.2354, 0.5547]],

        [[1.0599, 0.0000, 0.6416,  ..., 0.0000, 0.0000, 0.0000],
         [1.3901, 0.6719, 0.3476,  ..., 0.0000, 0.4370, 1.3253],
         [0.0000, 0.3019, 0.1287,  ..., 0.2983, 0.0000, 0.7577],
         ...,
         [0.0000, 0.8541, 3.1204,  ..., 0.1747, 0.5011, 1.2759],
         [0.0000, 0.0000, 0.0000,  ..., 0.6313, 0.0000, 0.0000],
         [0.3892, 0.0000, 0.0000,  ..., 1.9589, 0.0000, 0.0000]],

        [[0.0000, 0.8053, 0.0000,  ..., 0.1088, 0.0000, 0.0000],
         [0.7531, 0.0000, 1.2980,  ..., 0.1642, 0.2821, 0.5737],
         [0.9295, 0.3634, 0.6404,  ..., 0.0000, 0.6262, 0.

In [32]:
x

tensor([[[2.0981, 0.4984, 0.1248,  ..., 0.7762, 1.4056, 0.0000],
         [0.7291, 0.0000, 0.6834,  ..., 0.0000, 0.0000, 0.9463],
         [0.3137, 0.4641, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 2.5350, 0.0236, 1.4803],
         [1.1855, 0.1431, 1.3255,  ..., 0.0000, 0.5620, 1.5636],
         [0.7161, 0.0000, 0.6960,  ..., 0.9799, 1.2354, 0.5547]],

        [[1.0599, 0.0000, 0.6416,  ..., 0.0000, 0.0000, 0.0000],
         [1.3901, 0.6719, 0.3476,  ..., 0.0000, 0.4370, 1.3253],
         [0.0000, 0.3019, 0.1287,  ..., 0.2983, 0.0000, 0.7577],
         ...,
         [0.0000, 0.8541, 3.1204,  ..., 0.1747, 0.5011, 1.2759],
         [0.0000, 0.0000, 0.0000,  ..., 0.6313, 0.0000, 0.0000],
         [0.3892, 0.0000, 0.0000,  ..., 1.9589, 0.0000, 0.0000]],

        [[0.0000, 0.8053, 0.0000,  ..., 0.1088, 0.0000, 0.0000],
         [0.7531, 0.0000, 1.2980,  ..., 0.1642, 0.2821, 0.5737],
         [0.9295, 0.3634, 0.6404,  ..., 0.0000, 0.6262, 0.

## Functional

In [50]:
from torch.nn import functional as F

torch.manual_seed(32)

In [51]:
x = torch.randn(32, 32)

In [52]:
torch.rand(32, 32)

tensor([[0.2922, 0.9632, 0.5838,  ..., 0.5542, 0.5348, 0.3483],
        [0.3209, 0.4847, 0.2074,  ..., 0.2870, 0.7541, 0.4426],
        [0.7502, 0.0554, 0.7595,  ..., 0.5606, 0.8517, 0.3874],
        ...,
        [0.3870, 0.0470, 0.6820,  ..., 0.0040, 0.1531, 0.1144],
        [0.8491, 0.0643, 0.3198,  ..., 0.4112, 0.5913, 0.7734],
        [0.4611, 0.7609, 0.5597,  ..., 0.3601, 0.0304, 0.1999]])

In [53]:
x

tensor([[-1.7416, -0.3635,  0.9803,  ..., -1.8166,  0.7760, -0.6707],
        [ 0.7373, -0.6260,  0.3806,  ..., -0.0835, -0.5678,  0.2669],
        [ 0.0671,  0.1321, -0.6149,  ...,  0.4757,  1.0590,  0.3943],
        ...,
        [ 0.5485, -0.6834,  0.3442,  ..., -1.0146,  0.1095, -0.9289],
        [-0.1387,  0.9369,  2.2400,  ..., -0.5118, -0.1941,  1.3058],
        [ 0.0916, -0.0401, -1.3731,  ..., -0.9937, -1.3188, -1.6006]])

In [54]:
F.relu(x)

tensor([[0.0000, 0.0000, 0.9803,  ..., 0.0000, 0.7760, 0.0000],
        [0.7373, 0.0000, 0.3806,  ..., 0.0000, 0.0000, 0.2669],
        [0.0671, 0.1321, 0.0000,  ..., 0.4757, 1.0590, 0.3943],
        ...,
        [0.5485, 0.0000, 0.3442,  ..., 0.0000, 0.1095, 0.0000],
        [0.0000, 0.9369, 2.2400,  ..., 0.0000, 0.0000, 1.3058],
        [0.0916, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]])

In [55]:
assert (x.relu() == F.relu(x)).all()

## Non Linear

In [183]:
class Model_With_Residual(nn.Module):
    def __init__(self, in_features=2, out_features=2):
        super().__init__()
        self.inp = nn.Linear(in_features=in_features, out_features=10)
        self.layer2 = nn.Linear(10, 10)
        # self.non_linear = lambda x:F.relu(x)**.5
        self.layer3 = nn.Linear(10, 10)
        self.final = nn.Linear(in_features=10, out_features=out_features)
        print(self.count_params())

    def forward(self, x):
        out = self.inp(x)

        out = out + self.layer2(out.relu())

        out = out + self.layer3(out).relu()
        out = self.non_linear(out)
        out = self.final(out)
        return out

    def count_params(self):
        return sum([p.view(-1).shape[0] for p in self.parameters()])

    def print_variance(self):
        pass

In [184]:
model = Model_With_Residual(in_features=32, out_features=10)

660


In [185]:
model

Model_With_Residual(
  (inp): Linear(in_features=32, out_features=10, bias=True)
  (layer2): Linear(in_features=10, out_features=10, bias=True)
  (layer3): Linear(in_features=10, out_features=10, bias=True)
  (final): Linear(in_features=10, out_features=10, bias=True)
)

In [186]:
in_features = 10
out_features = 32
x = torch.randn(10, 32)

In [187]:
out1 = model(x)

In [188]:
out

tensor([[0.0000, 0.0420, 0.0000, 0.2902, 0.0000, 0.0000, 0.0449, 0.0000, 0.4522,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.1378, 0.0000, 0.0000, 0.0000, 0.0000, 0.3276,
         0.0000],
        [0.0000, 0.0855, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0352, 0.2028,
         0.0000],
        [0.0081, 0.0000, 0.0000, 0.0090, 0.0433, 0.1712, 0.0000, 0.0000, 0.0000,
         0.2853],
        [0.7912, 0.0000, 0.0000, 0.0000, 0.0000, 0.0118, 0.0000, 0.0000, 0.0037,
         0.2001],
        [0.0000, 0.0000, 0.0166, 0.2321, 0.0000, 0.1781, 0.0000, 0.0000, 0.0000,
         0.1102],
        [0.0000, 0.2643, 0.0000, 0.0365, 0.0321, 0.4161, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.1030, 0.0000, 0.3575, 0.2451, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.1639],
        [0.1636, 0.0912, 0.0000, 0.0516, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.1827],
        [0.1981, 0.0000, 0.0000, 0.1648, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]], grad_fn=<

In [149]:
out1

tensor([[0.1388, 0.0000, 0.0000, 0.2336, 0.0000, 0.0000, 0.5762, 0.2842, 0.5062,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.4855, 0.0000, 0.0824, 0.9590, 0.4791, 0.8904,
         0.0593],
        [0.0000, 0.5389, 0.0000, 0.3281, 0.0000, 0.0000, 0.1902, 0.5213, 0.6120,
         0.0000],
        [0.3978, 0.3937, 0.0544, 0.6436, 0.0000, 0.4155, 0.1366, 0.6576, 0.2127,
         0.0000],
        [0.0000, 0.2496, 0.1597, 0.0000, 0.0635, 0.0000, 0.4332, 1.5621, 0.3878,
         0.0000],
        [0.0370, 0.3993, 0.0000, 0.3332, 0.0000, 0.0336, 0.5847, 0.0996, 0.5919,
         0.0000],
        [0.0000, 0.4418, 0.0000, 0.4013, 0.0000, 0.0000, 0.2604, 0.4104, 0.6171,
         0.0000],
        [0.0000, 0.0000, 0.4150, 0.0000, 0.0000, 0.1104, 0.4446, 0.5568, 0.0000,
         0.0000],
        [0.0897, 0.0000, 0.0000, 0.4086, 0.0000, 0.0000, 0.5631, 0.5383, 0.7634,
         0.0903],
        [0.0000, 0.3098, 0.0470, 0.7892, 0.0000, 0.0000, 0.0000, 0.6106, 0.3075,
         0.0000]], grad_fn=<

In [153]:
out2 = model(x)

In [154]:
out2

tensor([[0.0000, 0.5918, 0.0000, 0.0000, 0.0000, 0.2539, 0.0000, 0.0000, 0.2408,
         0.0000],
        [0.0000, 0.3537, 0.0000, 0.1745, 0.0000, 0.1343, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.1912, 0.0000, 0.1607, 0.0000, 0.0000, 0.0268, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1245, 0.0000, 0.1260, 0.1234,
         0.0382],
        [0.4304, 0.4379, 0.0000, 0.0000, 0.0000, 0.5253, 0.0000, 0.6064, 0.0000,
         0.1991],
        [0.0000, 0.1086, 0.0000, 0.1666, 0.0000, 0.1216, 0.0000, 0.0000, 0.2169,
         0.0000],
        [0.1430, 0.0000, 0.0000, 0.0000, 0.0000, 0.0932, 0.3834, 0.2034, 0.2024,
         0.0000],
        [0.2163, 0.4444, 0.0000, 0.0000, 0.0000, 0.6492, 0.0000, 0.1092, 0.4842,
         0.0000],
        [0.0000, 0.0724, 0.0000, 0.1792, 0.0000, 0.3155, 0.0000, 0.0000, 0.2140,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0800, 0.0000, 0.0577, 0.0000, 0.0000, 0.0000,
         0.0000]], grad_fn=<

In [ ]:
last_check = model(x)

In [195]:
# todo
class Model_With_Residual(nn.Module):
    def __init__(self, in_features=2, out_features=2):
        super().__init__()
        self.inp = nn.Linear(in_features=in_features, out_features=10)
        self.layer2 = nn.Linear(10, 10)
        self.non_linear = lambda x: F.relu(x) ** 0.5
        self.layer3 = nn.Linear(10, 10)
        self.final = nn.Linear(in_features=10, out_features=out_features)
        print(self.count_params())

    def forward(self, x):
        out = self.inp(x)

        out = out + self.layer2(out.relu())

        out = out + self.layer3(out).relu()
        out = self.non_linear(out)
        out = self.final(out)
        return out

    def count_params(self):
        return sum([p.view(-1).shape[0] for p in self.parameters()])

    def print_variance(self):
        pass

In [196]:
model2 = Model_With_Residual(out_features, in_features)

660


In [197]:
model2(x)

tensor([[ 0.5835,  0.0218, -0.0152,  0.0236, -0.3501,  0.8056,  0.3060, -0.0294,
         -0.2924,  0.0412],
        [ 0.7909,  0.1722, -0.6779,  0.0566,  0.1405,  0.3557,  0.1949, -0.7976,
          0.0339,  0.3271],
        [ 0.8618,  0.2003, -0.5287, -0.1113, -0.1185,  0.5649,  0.1233, -0.5028,
         -0.0879,  0.1505],
        [ 0.2542,  0.8467, -0.5809, -0.0623, -0.2714,  0.9908,  0.4513, -0.0259,
         -0.2009,  0.2327],
        [ 0.6125,  0.7181, -0.5957, -0.3210,  0.2168,  0.8709,  0.6626, -0.3569,
         -0.1752,  0.4747],
        [ 0.3648, -0.1199, -0.1740,  0.1002, -0.1797,  0.0638,  0.0296, -0.0311,
          0.0151,  0.0050],
        [ 0.6431,  0.3049, -0.2571, -0.0567,  0.0012,  0.7678,  0.3368, -0.0034,
         -0.2840,  0.3592],
        [ 0.5248,  0.4880, -0.4936, -0.0864, -0.2313,  0.7198,  0.2891, -0.0379,
         -0.1862,  0.2692],
        [ 0.3645,  0.8033, -0.4650, -0.4342, -0.0092,  0.8667,  0.6689,  0.0757,
         -0.3168,  0.3746],
        [ 0.0829,  