## Multinomial and Bernoulli Naive Bayes

For understanding Multinomial and Bernoulli Naive Bayes, we will start with a small example and understand the end to end process. In another notebook, we will build a full-fledged email spam classifier.

To start with, let's take a few sentences and classify them in two different classes - *education* or *cinema*. Each sentence will represent one document. In real-world cases, a document be any piece of text such as an email, a news article, a book review, a tweet etc.
The analysis and the algorithm involved doesn’t depend on the type of document we use.

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
df = pd.read_csv("example_train.csv")

In [3]:
df

,Document,Class
0,Upgrad is a great educational institution.,education
1,Educational greatness depends on ethics,education
2,A story of great ethics and educational greatness,education
3,Sholey is a great cinema,cinema
4,good movie depends on good story,cinema


In [4]:
df["Class_mapped"] = df["Class"].map({"cinema": 0, "education": 1})

In [5]:
df

,Document,Class,Class_mapped
0,Upgrad is a great educational institution.,education,1
1,Educational greatness depends on ethics,education,1
2,A story of great ethics and educational greatness,education,1
3,Sholey is a great cinema,cinema,0
4,good movie depends on good story,cinema,0


In [6]:
df.drop("Class", axis=1, inplace=True)

In [7]:
# Converting data frame into numpy array
train = df.values
X_train = train[:, 0]
y_train = train[:, 1]

In [8]:
y_train.dtype

dtype('O')

In [9]:
# Converting into integer type
y_train = y_train.astype("int")

In [10]:
X_train, y_train

(array(['Upgrad is a great educational institution.',
        'Educational greatness depends on ethics',
        'A story of great ethics and educational greatness',
        'Sholey is a great cinema', 'good movie depends on good story'],
       dtype=object),
 array([1, 1, 1, 0, 0]))

In [11]:
y_train.dtype

dtype('int64')

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

help(CountVectorizer)

Help on class CountVectorizer in module sklearn.feature_extraction.text:

class CountVectorizer(_VectorizerMixin, sklearn.base.BaseEstimator)
 |  CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)
 |
 |  Convert a collection of text documents to a matrix of token counts.
 |
 |  This implementation produces a sparse representation of the counts using
 |  scipy.sparse.csr_matrix.
 |
 |  If you do not provide an a-priori dictionary and you do not use an analyzer
 |  that does some kind of feature selection then the number of features will
 |  be equal to the vocabulary size found by analyzing the data.
 |
 |  For an efficiency comparison of the different feature extractors, see
 |  :ref:`sphx_glr_auto_examp

In [13]:
vectorizer = CountVectorizer()

In [14]:
vectorizer.fit(X_train)

,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None
,stop_words,None
,token_pattern,'(?u)\\b\\w\\w+\\b'
,ngram_range,"(1, ...)"
,analyzer,'word'


In [15]:
dir(vectorizer)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_limit_features',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr

In [16]:
vectorizer.vocabulary_

{'upgrad': 15,
 'is': 9,
 'great': 6,
 'educational': 3,
 'institution': 8,
 'greatness': 7,
 'depends': 2,
 'on': 12,
 'ethics': 4,
 'story': 14,
 'of': 11,
 'and': 0,
 'sholey': 13,
 'cinema': 1,
 'good': 5,
 'movie': 10}

## Removing Stop Words

In [17]:
vec = CountVectorizer(stop_words="english")

In [18]:
vec.fit(X_train)

,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None
,stop_words,'english'
,token_pattern,'(?u)\\b\\w\\w+\\b'
,ngram_range,"(1, ...)"
,analyzer,'word'


In [19]:
vec.vocabulary_

{'upgrad': 11,
 'great': 5,
 'educational': 2,
 'institution': 7,
 'greatness': 6,
 'depends': 1,
 'ethics': 3,
 'story': 10,
 'sholey': 9,
 'cinema': 0,
 'good': 4,
 'movie': 8}

In [20]:
print(
    f"Features: {vec.get_feature_names_out()}, Length: {len(vec.get_feature_names_out())}"
)

Features: ['cinema' 'depends' 'educational' 'ethics' 'good' 'great' 'greatness'
 'institution' 'movie' 'sholey' 'story' 'upgrad'], Length: 12


In [21]:
X_transform = vec.transform(X_train)
str(X_transform)

'  (0, 2)\t1\n  (0, 5)\t1\n  (0, 7)\t1\n  (0, 11)\t1\n  (1, 1)\t1\n  (1, 2)\t1\n  (1, 3)\t1\n  (1, 6)\t1\n  (2, 2)\t1\n  (2, 3)\t1\n  (2, 5)\t1\n  (2, 6)\t1\n  (2, 10)\t1\n  (3, 0)\t1\n  (3, 5)\t1\n  (3, 9)\t1\n  (4, 1)\t1\n  (4, 4)\t2\n  (4, 8)\t1\n  (4, 10)\t1'

In [22]:
print(X_transform)

  (0, 2)	1
  (0, 5)	1
  (0, 7)	1
  (0, 11)	1
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (1, 6)	1
  (2, 2)	1
  (2, 3)	1
  (2, 5)	1
  (2, 6)	1
  (2, 10)	1
  (3, 0)	1
  (3, 5)	1
  (3, 9)	1
  (4, 1)	1
  (4, 4)	2
  (4, 8)	1
  (4, 10)	1


In [23]:
X_transform.toarray()

array([[0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0]])

In [24]:
pd.DataFrame(X_transform.toarray(), columns=vec.get_feature_names_out())

,cinema,depends,educational,ethics,good,great,greatness,institution,movie,sholey,story,upgrad
0,0,0,1,0,0,1,0,1,0,0,0,1
1,0,1,1,1,0,0,1,0,0,0,0,0
2,0,0,1,1,0,1,1,0,0,0,1,0
3,1,0,0,0,0,1,0,0,0,1,0,0
4,0,1,0,0,2,0,0,0,1,0,1,0


In [25]:
X_transform.shape

(5, 12)

## Doing it on test set

In [26]:
df_test = pd.read_csv("example_test.csv")

In [27]:
df_test

,Document,Class
0,very good educational institution,education


In [28]:
df_test["Class"] = df_test["Class"].map({"cinema": 0, "education": 1})

In [29]:
test = df_test.values
X_test = test[:, 0]
y_test = test[:, 1]
print(X_test, y_test)

['very good educational institution'] [1]


In [30]:
X_test_transformed = vec.transform(X_test)
X_test_transformed

<1x12 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [31]:
print(X_test_transformed)

  (0, 2)	1
  (0, 4)	1
  (0, 7)	1


In [32]:
# convert to non-sparse array
X_test = X_test_transformed.toarray()
X_test

array([[0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0]])

Consider first 4 rows of the output: (0,2), (0,5), (0,7) and (0,11). It says that the first document (index 0) has 7th , 2nd , 5th and 11th 'word' present in the document, and that they appear only once in the document- indicated by the right hand column entry.


Similarly, consider the entry (4,4) (third from bottom). It says that the fifth document has the fifth word present twice. Indeed, the 5th word('good') appears twice in the 5th document.

## Building model using Multinomial Naive Bayes

In [33]:
# Importing
from sklearn.naive_bayes import MultinomialNB

# Instantiation
mnb = MultinomialNB()

# Fitting

mnb.fit(X_transform, y_train)

# Prediction

mnb.predict(X_test)

array([1])

In [34]:
mnb.predict_proba(X_test)

array([[0.32808399, 0.67191601]])

In [35]:
print("Probability of class cinema predicted:", mnb.predict_proba(X_test)[:, 0][0])
print("Probability of class education predicted:", mnb.predict_proba(X_test)[:, 1][0])

Probability of class cinema predicted: 0.3280839895013124
Probability of class education predicted: 0.6719160104986874


## Building model with Bernoulli

In [36]:
import sklearn.naive_bayes as naive_bayes

##  bernoulli instantiation

bn = naive_bayes.BernoulliNB()

## fit

bn.fit(X_transform, y_train)

bn.predict_proba(X_test)

array([[0.2326374, 0.7673626]])

In [43]:
a = 0.5
b_a = 0.99

b = b_a * a

In [44]:
b

0.495

In [45]:
a_b = b_a * a / b
a_b

1.0