In [1]:
import numpy as np
import pandas as pd
import sklearn
import requests
import pickle

In [11]:
response = requests.get(
    "https://github.com/greydanus/mnist1d/raw/master/mnist1d_data.pkl"
)
URL = "https://github.com/greydanus/mnist1d/raw/master/mnist1d_data.pkl"

In [8]:
if response.status_code == 200:
    pickle.dump(response.content, open("mnist1d_data.pkl", "wb"))

In [13]:
from urllib.request import urlopen

with open("mnist1d_data.pkl", "r") as f:
    data = pickle.load(urlopen(URL))

In [14]:
data.keys()

dict_keys(['x', 'x_test', 'y', 'y_test', 't', 'templates'])

In [15]:
data["x"]

array([[-0.33200567, -0.47191037, -0.77869708, ..., -0.7167305 ,
        -0.96195825, -0.89016639],
       [ 1.96548088,  2.30021254,  2.21339278, ..., -1.68751297,
        -1.42642212, -1.36421511],
       [-0.01930303,  0.07863308,  0.62488909, ..., -1.08555748,
        -1.79809121, -2.3153282 ],
       ...,
       [-1.69449348, -1.2805858 , -0.65125255, ..., -0.72365942,
        -0.38266551, -0.03165042],
       [ 0.99646721,  0.80844603,  0.1553411 , ..., -0.30286571,
        -0.28555128, -0.1183879 ],
       [-0.6939948 , -0.27532169,  0.29267968, ..., -1.21624513,
        -1.4649417 , -1.65099286]], shape=(4000, 40))

In [16]:
data["y"]

array([2, 6, 4, ..., 5, 4, 8], shape=(4000,))

In [22]:
df = pd.DataFrame.from_dict(
    {
        "x_train": data["x"],
        "x_test": data["x_test"],
        "y_train": np.array(data["y"]).reshape(-1, 1),
        "y_test": np.array(data["y_test"]).reshape(-1, 1),
    }
)

ValueError: Per-column arrays must each be 1-dimensional

In [23]:
data["x"]

array([[-0.33200567, -0.47191037, -0.77869708, ..., -0.7167305 ,
        -0.96195825, -0.89016639],
       [ 1.96548088,  2.30021254,  2.21339278, ..., -1.68751297,
        -1.42642212, -1.36421511],
       [-0.01930303,  0.07863308,  0.62488909, ..., -1.08555748,
        -1.79809121, -2.3153282 ],
       ...,
       [-1.69449348, -1.2805858 , -0.65125255, ..., -0.72365942,
        -0.38266551, -0.03165042],
       [ 0.99646721,  0.80844603,  0.1553411 , ..., -0.30286571,
        -0.28555128, -0.1183879 ],
       [-0.6939948 , -0.27532169,  0.29267968, ..., -1.21624513,
        -1.4649417 , -1.65099286]], shape=(4000, 40))

In [21]:
np.array(data["y"]).reshape(-1, 1)

array([[2],
       [6],
       [4],
       ...,
       [5],
       [4],
       [8]], shape=(4000, 1))