In [1]:
import torch

torch.autograd.set_detect_anomaly(True)

In [2]:
import pdb

pdb.set_trace()

> /var/folders/px/m0g9wbyn1sv678fsx9lgsm600000gn/T/ipykernel_7575/474236900.py(2)<module>()
      1 import pdb
----> 2 pdb.set_trace()

--KeyboardInterrupt--

KeyboardInterrupt: Interrupted by user


In [26]:
x = torch.ones(2, 2, requires_grad=True)

In [4]:
x += 1

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [5]:
x = x + 1

In [6]:
x

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [27]:
y = x.clone()

In [28]:
y[0, 0] = 1

In [11]:
y

tensor([[1., 2.],
        [2., 2.]], grad_fn=<CopySlices>)

In [29]:
y.sum().backward()

In [13]:
y.grad

/var/folders/px/m0g9wbyn1sv678fsx9lgsm600000gn/T/ipykernel_7575/486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /Users/runner/work/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:498.)
  y.grad


In [30]:
x.grad

tensor([[0., 1.],
        [1., 1.]])

In [31]:
z = y**2

In [32]:
z

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)

In [34]:
z.requires_grad

True

In [17]:
y.sum().backward()

In [18]:
x.grad

/var/folders/px/m0g9wbyn1sv678fsx9lgsm600000gn/T/ipykernel_7575/3730140797.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /Users/runner/work/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:498.)
  x.grad


In [19]:
x = torch.linspace(0, 5, 100, requires_grad=True)

In [20]:
x

tensor([0.0000, 0.0505, 0.1010, 0.1515, 0.2020, 0.2525, 0.3030, 0.3535, 0.4040,
        0.4545, 0.5051, 0.5556, 0.6061, 0.6566, 0.7071, 0.7576, 0.8081, 0.8586,
        0.9091, 0.9596, 1.0101, 1.0606, 1.1111, 1.1616, 1.2121, 1.2626, 1.3131,
        1.3636, 1.4141, 1.4646, 1.5152, 1.5657, 1.6162, 1.6667, 1.7172, 1.7677,
        1.8182, 1.8687, 1.9192, 1.9697, 2.0202, 2.0707, 2.1212, 2.1717, 2.2222,
        2.2727, 2.3232, 2.3737, 2.4242, 2.4747, 2.5253, 2.5758, 2.6263, 2.6768,
        2.7273, 2.7778, 2.8283, 2.8788, 2.9293, 2.9798, 3.0303, 3.0808, 3.1313,
        3.1818, 3.2323, 3.2828, 3.3333, 3.3838, 3.4343, 3.4848, 3.5354, 3.5859,
        3.6364, 3.6869, 3.7374, 3.7879, 3.8384, 3.8889, 3.9394, 3.9899, 4.0404,
        4.0909, 4.1414, 4.1919, 4.2424, 4.2929, 4.3434, 4.3939, 4.4444, 4.4949,
        4.5455, 4.5960, 4.6465, 4.6970, 4.7475, 4.7980, 4.8485, 4.8990, 4.9495,
        5.0000], requires_grad=True)

In [21]:
y = x.cos()

In [22]:
y

tensor([ 1.0000,  0.9987,  0.9949,  0.9885,  0.9797,  0.9683,  0.9544,  0.9382,
         0.9195,  0.8985,  0.8752,  0.8496,  0.8219,  0.7921,  0.7603,  0.7265,
         0.6909,  0.6535,  0.6145,  0.5739,  0.5318,  0.4883,  0.4437,  0.3979,
         0.3510,  0.3033,  0.2548,  0.2057,  0.1560,  0.1060,  0.0556,  0.0051,
        -0.0453, -0.0957, -0.1459, -0.1956, -0.2449, -0.2935, -0.3414, -0.3884,
        -0.4344, -0.4793, -0.5230, -0.5654, -0.6063, -0.6457, -0.6834, -0.7194,
        -0.7536, -0.7858, -0.8160, -0.8441, -0.8701, -0.8939, -0.9154, -0.9345,
        -0.9513, -0.9657, -0.9775, -0.9869, -0.9938, -0.9982, -0.9999, -0.9992,
        -0.9959, -0.9900, -0.9817, -0.9708, -0.9575, -0.9417, -0.9235, -0.9029,
        -0.8801, -0.8550, -0.8277, -0.7983, -0.7669, -0.7335, -0.6983, -0.6613,
        -0.6225, -0.5822, -0.5405, -0.4973, -0.4529, -0.4073, -0.3606, -0.3131,
        -0.2647, -0.2157, -0.1662, -0.1162, -0.0659, -0.0154,  0.0351,  0.0855,
         0.1357,  0.1855,  0.2349,  0.28

In [24]:
y.sum().backward()

In [25]:
x.grad

tensor([-0.0000, -0.0505, -0.1008, -0.1509, -0.2006, -0.2498, -0.2984, -0.3462,
        -0.3931, -0.4391, -0.4839, -0.5274, -0.5696, -0.6104, -0.6496, -0.6872,
        -0.7230, -0.7569, -0.7889, -0.8190, -0.8469, -0.8727, -0.8962, -0.9174,
        -0.9364, -0.9529, -0.9670, -0.9786, -0.9878, -0.9944, -0.9985, -1.0000,
        -0.9990, -0.9954, -0.9893, -0.9807, -0.9696, -0.9560, -0.9399, -0.9215,
        -0.9007, -0.8776, -0.8523, -0.8248, -0.7952, -0.7636, -0.7300, -0.6946,
        -0.6574, -0.6185, -0.5781, -0.5361, -0.4928, -0.4483, -0.4026, -0.3558,
        -0.3082, -0.2598, -0.2107, -0.1611, -0.1111, -0.0607, -0.0103,  0.0402,
         0.0906,  0.1408,  0.1906,  0.2399,  0.2886,  0.3366,  0.3837,  0.4298,
         0.4748,  0.5187,  0.5612,  0.6022,  0.6418,  0.6797,  0.7158,  0.7502,
         0.7826,  0.8130,  0.8414,  0.8676,  0.8916,  0.9133,  0.9327,  0.9497,
         0.9643,  0.9765,  0.9861,  0.9932,  0.9978,  0.9999,  0.9994,  0.9963,
         0.9908,  0.9826,  0.9720,  0.95

In [35]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [36]:
x.permute(0, 1)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PermuteBackward0>)

In [37]:
x.requires_grad = False

In [38]:
x[0, 0] = 2

In [39]:
x.permute(0, 1)

tensor([[2., 1.],
        [1., 1.]])

In [40]:
x.permute(1, 0)

tensor([[2., 1.],
        [1., 1.]])

In [54]:
a = x.permute(1, 0)

In [55]:
id(a), id(x)

(4737359312, 4734954448)

In [53]:
from IPython.display import display

display(x.view(4, 1))
display(x.view(1, 4))

tensor([[2.],
        [1.],
        [1.],
        [1.]])

tensor([[2., 1., 1., 1.]])