In [18]:
import numpy as np
import tensorflow as tn
from numpy import dtype

In [19]:
tn.__version__

'2.20.0'

In [20]:
%%time
a = np.array([[1, 2], [3, 4]] * 5)
print(a)

[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]
CPU times: total: 31.2 ms
Wall time: 7.85 ms


In [21]:
%%time
b = tn.constant([[1, 2], [3, 4]] * 5)
print(b)

tf.Tensor(
[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]], shape=(10, 2), dtype=int32)
CPU times: total: 0 ns
Wall time: 0 ns


In [31]:
c = np.random.randn(2, 2, 2, 2)
print(c)
d = tn.constant(c)
print(d)

[[[[ 1.58864857  0.42224155]
   [-1.7116479   0.11496255]]

  [[-1.96161833  1.16132832]
   [-0.71983944 -0.25097756]]]


 [[[ 0.92254663  0.68717673]
   [-0.28389391  1.88375586]]

  [[ 0.33339995 -0.25945927]
   [ 0.5273814  -1.43832659]]]]
tf.Tensor(
[[[[ 1.58864857  0.42224155]
   [-1.7116479   0.11496255]]

  [[-1.96161833  1.16132832]
   [-0.71983944 -0.25097756]]]


 [[[ 0.92254663  0.68717673]
   [-0.28389391  1.88375586]]

  [[ 0.33339995 -0.25945927]
   [ 0.5273814  -1.43832659]]]], shape=(2, 2, 2, 2), dtype=float64)


In [32]:
print(c.mean())
print(c.std())
c = c + 1
print("printing mean", np.mean(c))
print("printing std", np.std(c))
d = tn.constant(c)
print(d)

0.06347991023979777
1.0850168670996625
printing mean 1.0634799102397978
printing std 1.0850168670996623
tf.Tensor(
[[[[ 2.58864857  1.42224155]
   [-0.7116479   1.11496255]]

  [[-0.96161833  2.16132832]
   [ 0.28016056  0.74902244]]]


 [[[ 1.92254663  1.68717673]
   [ 0.71610609  2.88375586]]

  [[ 1.33339995  0.74054073]
   [ 1.5273814  -0.43832659]]]], shape=(2, 2, 2, 2), dtype=float64)


In [33]:
a = tn.Variable([range(5)] * 5)
b = tn.Variable([range(5, 10)] * 5)
print(a)
print(b)
print(a + b)

<tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])>
<tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])>
tf.Tensor(
[[ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]], shape=(5, 5), dtype=int32)


In [34]:
a = tn.random.normal((2, 2))

In [35]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.4178268 ,  0.26474595],
       [ 0.94446963, -0.248485  ]], dtype=float32)>

In [36]:
b = a**2
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.17457923, 0.07009041],
       [0.8920229 , 0.06174479]], dtype=float32)>

In [41]:
W = tn.Variable(
    [[1, 1, 1, 1], [2, 3, 0, -1], [-3, 4, 1, 2], [1, 2, -1, 1]], dtype=tn.float32
)
y = tn.Variable([[13], [-1], [10], [1]], dtype=tn.float32)
W_inverse = tn.linalg.inv(W)
ans = tn.cast(tn.round(tn.matmul(W_inverse, y)), dtype=tn.int32)

print(ans)

tf.Tensor(
[[2]
 [0]
 [6]
 [5]], shape=(4, 1), dtype=int32)


In [71]:
w1 = tn.Variable([[0.5, 1, -1.2]])
print(w1.shape)
X = tn.Variable([[0.2], [1], [0.5]])
ans = w1 @ X
ans = ans + 0.01

(1, 3)


In [72]:
ans = 1 / (1 + np.e**-ans)

In [73]:
ans

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.62480646]], dtype=float32)>