In [30]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [78]:
df = pd.DataFrame(
    [
        np.array([1, 0, 3, 7, 2]),
        np.array([5, 7, 10, 0, 7]),
        np.array([4, 12, 0, 2, 0]),
        np.array([5, 7, 10, 0, 7]),
        np.array([5, 7, 10, 0, 7]),
    ],
    columns=["a", "b", "c", "d", "e"],
)

In [79]:
df

,a,b,c,d,e
0,1,0,3,7,2
1,5,7,10,0,7
2,4,12,0,2,0
3,5,7,10,0,7
4,5,7,10,0,7


In [107]:
filter = pd.DataFrame(
    [
        np.zeros(3),
        np.array([1, 0, 1]),
        np.array([-1, 0, 0]),
        np.array([0, 1, 0]),
        np.zeros(3),
    ],
    columns=None,
)

In [117]:
np.linalg.matmul(df1.T, filter)

,0,1,2
a,1.0,0.0,5.0
b,-5.0,1.0,7.0
c,10.0,11.0,10.0
d,-2.0,1.0,0.0
e,7.0,3.0,7.0


In [83]:
np.multiply(df, filter)

,a,b,c,d,e,0,1,2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [77]:
df.shape

(5, 5)

In [41]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])

In [42]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [44]:
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
tf.transpose(b)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [45]:
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [85]:
tf.multiply(df, filter)

<tf.Tensor: shape=(5, 3), dtype=int64, numpy=
array([[-3,  7,  0],
       [-3,  0,  7],
       [12,  2, 12],
       [-3,  0,  7],
       [-3,  0,  7]])>

In [58]:
tf.add(df[:3].T, filter)

<tf.Tensor: shape=(5, 3), dtype=int64, numpy=
array([[ 2,  5,  5],
       [-1,  7, 12],
       [ 3, 11,  0],
       [ 7,  0,  2],
       [ 2,  7,  0]])>

In [59]:
df1 = pd.read_clipboard()

In [60]:
df1

,b,=,"tf.constant([7,","8,","9,","10,","11,","12],","shape=[3,",2])


In [94]:
df1 = pd.read_clipboard()

In [95]:
df1

,a,b,c,d,e
0,1,0,3,7,2
1,5,7,10,0,7
2,4,12,0,2,0
3,0,1,11,1,3
4,10,7,0,8,1


In [87]:
filter

,0,1,2
0,0.0,0.0,0.0
1,1.0,0.0,1.0
2,-1.0,0.0,0.0
3,0.0,1.0,0.0
4,0.0,0.0,0.0


In [105]:
df1 = df1.apply(lambda x: x.astype("int32"))

In [115]:
filter

,0,1,2
0,0.0,0.0,0.0
1,1.0,0.0,1.0
2,-1.0,0.0,0.0
3,0.0,1.0,0.0
4,0.0,0.0,0.0


In [118]:
df1.to_csv("sample.csv")

In [121]:
filter[:1, :1]

KeyError: (slice(None, 1, None), slice(None, 1, None))

In [129]:
np.arange((0,25,dtupe=),shape=[5,5])


In [130]:
lst

,0,1,2,3,4
0,0,1,2,3,4
1,0,1,2,3,4
2,0,1,2,3,4
3,0,1,2,3,4
4,0,1,2,3,4


In [131]:
b = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])

In [132]:
b

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [134]:
np.arange((13, 25, dtype=np.int32), shape=[2, 3, 2])

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (1454758763.py, line 1)

In [137]:
np.arange([0, 25], shape(5, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], dtype=int32)

In [138]:
np.arange(0, 5, 0.5, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [143]:
np.arange(-3, 4, 0.5, dtype=int).reshape(4, 3)

array([[-3, -2, -1],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [145]:
np.arange(0, 25, 1, dtype=int).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [146]:
df1

,a,b,c,d,e
0,1,0,3,7,2
1,5,7,10,0,7
2,4,12,0,2,0
3,0,1,11,1,3
4,10,7,0,8,1


In [152]:
x = filter[1:4]

In [153]:
x

,0,1,2
1,1.0,0.0,1.0
2,-1.0,0.0,0.0
3,0.0,1.0,0.0


In [164]:
a = df1.iloc[0:3][["a", "b", "c"]]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  0,  3],
       [-5,  0,  0],
       [ 0, 12,  0]], dtype=int32)>