In [2]:
import numpy as np

## convert into array

In [3]:
# Deine a NumPy array
heights = np.array([1,2,3,4,5,6,7,8])
heights

array([1, 2, 3, 4, 5, 6, 7, 8])

## multiply

In [5]:
# Multiple NumPy array with a scalar.
heights * 2.54

array([ 2.54,  5.08,  7.62, 10.16, 12.7 , 15.24, 17.78, 20.32])

## addition

In [6]:
# two NumPy array and perform '+' operation on that.
np1 = np.array([1,2,3])
np2 = np.array([4,5,6])
np3=np1 + np2
np3

array([5, 7, 9])

## check type

In [4]:
###   type of a NumPy array.
type(heights)

numpy.ndarray

## count number/size/shape

In [54]:
###   Count the number
a=len(heights)

b=heights.size

c=heights.shape

##### Print the structure of the 2-D Array
d=players.shape

print(a)
print(b)
print(c)
print(d)

8
8
(8,)
(7, 2)


##    Indexing on 1d 

In [9]:
##### Fetch the first element from the bmi array 

heights[0]

1

In [10]:
##### Fetch the last element from the bmi array 

heights[-1]

8

In [11]:
#####  Fetch the first 5 elements from the bmi array 

heights[0:5]

array([1, 2, 3, 4, 5])

In [12]:
##### Fetch the last 5 elements from the bmi array 

heights[-5:]

array([4, 5, 6, 7, 8])

In [13]:
###    Conditional Sub-Setting Arrays

a = heights < 5

b = heights[ heights<5]

print(a)
print(b)

[ True  True  True  True False False False False]
[1 2 3 4]


## max

In [14]:
###   Find the largest value
max(heights)

8

## min

In [15]:
##### Find lowest value

min(heights)

1

## sum

In [20]:
###   how to find out total/sun of array
total = heights.sum() 
total

36

## mean

In [17]:
##### Find average value

heights.mean()

4.5

In [22]:
# list of height and weight of the players.
players = [(74, 180), (74, 215), (72, 210), (72, 210), (73, 188), (69, 176), (69, 209)]

In [25]:
players = np.array(players)
players

array([[ 74, 180],
       [ 74, 215],
       [ 72, 210],
       [ 72, 210],
       [ 73, 188],
       [ 69, 176],
       [ 69, 209]])

## check dimension

In [33]:
##### Print the dimensions of the array

players.ndim

2

In [34]:
##### Print the data type of elements in the array

players.dtype

dtype('int32')

In [35]:
##### Print the size of a single item of the array

players.itemsize

4

## indexing on 2d

In [37]:
##### Fetch the first column from the array 

players[:, 0]

array([74, 74, 72, 72, 73, 69, 69])

In [39]:
##### Fetch the first row from the array 

players[0,:]

array([ 74, 180])

In [48]:
##### Creating array of ones

arr = np.ones(5)
arr
arr1=np.ones((5,3))
arr1

print('1st:',arr)
print('2nd:',arr1)

1st: [1. 1. 1. 1. 1.]
2nd: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [49]:
###  arange function
np.arange(3,35,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [55]:
##### Array of random numbers 

np.random.randint(2, size=10)

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 0])

In [56]:
##### 2D Array of random numbers 

np.random.random([3,4])

array([[0.63518622, 0.50821868, 0.90403918, 0.63642266],
       [0.84545451, 0.61798478, 0.08291789, 0.70362225],
       [0.5903629 , 0.25957644, 0.24552696, 0.29002456]])

In [57]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [18]:
import jovian

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ashutoshgole18/numpy-notes-as-per-my-understanding" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/ashutoshgole18/numpy-notes-as-per-my-understanding


'https://jovian.ai/ashutoshgole18/numpy-notes-as-per-my-understanding'