In [1]:
import numpy as np

In [2]:
X = np.array([[1, 0, 1, 0], [1, 0, 1, 1], [0, 0, 1, 1]])
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 0, 1, 1]])

In [3]:
y = np.array([[1], [1], [0]])
y

array([[1],
       [1],
       [0]])

In [9]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))  # 1/(1+np.exp(-x)) 1/(1+1/e^x)

In [13]:
def derivative_sigmoid(x):
    return 1 - 1 / np.exp(x)

In [25]:
epoch = 5000  # number of training iterations
lr = 0.1  # learning rate
inputlayer_neurons = X.shape[1]  # number of features in data set
hiddenlayer_neurons = 3  # number of hidden layers neurons
output_neurons = 1  # number of neurons at output layer

# initializing weight and bias
wh = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))
bh = np.random.uniform(size=(1, hiddenlayer_neurons))
wout = np.random.uniform(size=(hiddenlayer_neurons, output_neurons))
bout = np.random.uniform(size=(1, output_neurons))

In [21]:
# bh = np.random.uniform(size=(1,hidden_layer_neurons))
# wout = np.random.uniform(size=(hidden_layer_neurons,output_layer_neurons))
# bout = np.random.uniform(size=(1,output_layer_neurons))
# wh = np.random.uniform(size=(input_layer_neurons,output_layer_neurons))

In [22]:
bout

array([[0.47221304],
       [0.55397926],
       [0.15961081],
       [0.55244263]])

In [26]:
for i in range(epoch):
    # Forward Propogation
    hidden_layer_input1 = np.dot(X, wh)
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1 = np.dot(hiddenlayer_activations, wout)
    output_layer_input = output_layer_input1 + bout
    output = sigmoid(output_layer_input)

    # Backpropagation
    E = y - output
    slope_output_layer = derivative_sigmoid(output)
    slope_hidden_layer = derivative_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) * lr
    bout += np.sum(d_output, axis=0, keepdims=True) * lr
    wh += X.T.dot(d_hiddenlayer) * lr
    bh += np.sum(d_hiddenlayer, axis=0, keepdims=True) * lr

print("\n Output from the model:")
print(output)


 Output from the model:
[[0.99606253]
 [0.99606126]
 [0.09260282]]
