In [1]:
import numpy as np

In [12]:
a = np.array([[1 / 3, 1 / 3], [-1 / 3, 2 / 3]], dtype=np.float32)
b = np.array([[2, -1], [1, 1]], dtype=np.float32)

In [13]:
a @ b

array([[1., 0.],
       [0., 1.]], dtype=float32)

In [14]:
import torch

A = torch.tensor(a)
B = torch.tensor(b)

In [15]:
A @ B

tensor([[1., 0.],
        [0., 1.]])

In [10]:
A.dtype

torch.float64

In [11]:
B.dtype

torch.int64

In [16]:
B.inverse()

tensor([[ 0.3333,  0.3333],
        [-0.3333,  0.6667]])