## computation graph in torch

In [1]:
import torch

In [4]:
def compute_fn(a, b, c):
    node1 = torch.sub(a, b)
    node2 = torch.mul(node1, 2)
    node3 = torch.add(node2, c)
    return node3

In [5]:
print("Scalar Inputs:", compute_fn(torch.tensor(1), torch.tensor(2), torch.tensor(3)))

Scalar Inputs: tensor(1)


In [7]:
a = torch.tensor(3.0, requires_grad=True)

In [8]:
b = a * 2
b.backward()
print(a.grad)

tensor(2.)


## basic nn

In [48]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.5, requires_grad=True)
x = torch.tensor([1.4])
y = torch.tensor([2.1])

In [49]:
z = torch.mul(x, w) + b
z

tensor([1.9000], grad_fn=<AddBackward0>)

In [50]:
loss = (y - (x * w + b)) ** 2

In [51]:
loss.sum()

tensor(0.0400, grad_fn=<SumBackward0>)

In [52]:
loss.backward()

In [53]:
print(f"dl/dw: {w.grad}, dl/db: {b.grad}")

dl/dw: -0.5599997639656067, dl/db: -0.39999985694885254


In [54]:
# verifying
print(2 * x * ((w * x + b) - y))

tensor([-0.5600], grad_fn=<MulBackward0>)


In [55]:
from torch import nn

In [59]:
m = nn.Identity(3)
x = torch.tensor([[1, 1], [1, 1]])
out = m(x)
out

tensor([[1, 1],
        [1, 1]])

In [57]:
m

Identity()