In [1]:
import tensorflow as tf

## Basics

In [2]:
x = tf.Variable([1, 2])

In [3]:
b = dir(x)

In [4]:
x.assign([1, 2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [5]:
x.assign([3, 4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([3, 4], dtype=int32)>

In [6]:
x

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4], dtype=int32)>

In [7]:
x.name

'Variable:0'

In [8]:
x.dtype

tf.int32

In [9]:
y = tf.constant([1, 2, 3])

In [10]:
str(y)

'tf.Tensor([1 2 3], shape=(3,), dtype=int32)'

In [11]:
a = dir(y)

In [12]:
type(b)

list

In [13]:
set(a) in set(b)

False

In [14]:
set(b) == set(a)

False

In [15]:
set(b).difference(set(a))

{'SaveSliceInfo',
 '_OverloadAllOperators',
 '_OverloadOperator',
 '_TensorConversionFunction',
 '__abstractmethods__',
 '__composite_gradient__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__ipow__',
 '__irealdiv__',
 '__isub__',
 '__itruediv__',
 '__long__',
 '_abc_impl',
 '_add_trackable_child',
 '_add_variable_with_custom_getter',
 '_aggregation',
 '_as_graph_element',
 '_assign_dependencies',
 '_cached_shape_as_list',
 '_cached_value',
 '_caching_device',
 '_checkpoint_adapter',
 '_checkpoint_dependencies',
 '_constraint',
 '_consumers',
 '_convert_variables_to_tensors',
 '_copy_trackable_to_cpu',
 '_deferred_dependencies',
 '_dense_var_to_tensor',
 '_deserialization_dependencies',
 '_deserialize_from_proto',
 '_distribute_strategy',
 '_dtype',
 '_export_to_saved_model_graph',
 '_gather_saveables_for_checkpoint',
 '_get_save_slice_info',
 '_get_xla_sharding',
 '_graph_element',
 '_graph_key',
 '_handle',
 '_handle_deferred_dependencies',
 '_handle_name',
 '_in_graph_mode',
 '_init_f

In [16]:
x.value

<bound method BaseResourceVariable.value of <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4], dtype=int32)>>

In [17]:
z = y + 1

In [18]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [19]:
tf.rank(z)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [20]:
a1 = tf.Variable([[1, 2], [3, 3]])

In [21]:
tf.rank(a1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [22]:
a1.shape

TensorShape([2, 2])

In [23]:
x = tf.constant([[[0, 1], [2, 3], [4, 5]]] * 5)

In [24]:
x.shape

TensorShape([5, 3, 2])

In [25]:
print(x)

tf.Tensor(
[[[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]], shape=(5, 3, 2), dtype=int32)


In [26]:
import numpy as np

x_np = np.array([[[0, 1], [2, 3], [4, 5]]] * 5)

In [27]:
x_np.shape

(5, 3, 2)

In [28]:
print(x_np)

[[[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]]


In [29]:
x.numpy()

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]], dtype=int32)

In [30]:
a_np = np.random.randn(2, 2, 2, 2)
print(f"Numpy: {a_np.shape}")
a_tf = tf.constant(a_np)
print(f"Tensor: {a_tf.__str__()}")
print(f"Mean Numpy: {np.mean(a_np)}, Std Dev: {np.std(a_np)}")
# print(f"Mean Tensorflow: {tf.metrics.Mean(a_tf)}")

Numpy: (2, 2, 2, 2)
Tensor: tf.Tensor(
[[[[ 0.63388176 -0.67856607]
   [ 1.3028055   0.97135965]]

  [[ 0.22072657  1.37139928]
   [-0.61087355 -0.41436586]]]


 [[[-0.39461431 -1.09198368]
   [-0.50779564  0.53849384]]

  [[ 0.22501843  2.12778166]
   [-1.41541682 -0.3417986 ]]]], shape=(2, 2, 2, 2), dtype=float64)
Mean Numpy: 0.12100325999160594, Std Dev: 0.94662072846289


In [31]:
tf.ones([5, 5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [32]:
tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[1, 2], [3, 4]])
tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [34]:
print(tensor1)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [35]:
tf.reshape(tensor1, [4, 1])

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [36]:
np_x = np.array([[1, 2, 4], [3, 4, 5]])
print(np_x.shape)
np_transpose = np_x.reshape([3, 2])
np_x @ np_transpose

(2, 3)


array([[25, 28],
       [39, 43]])

In [37]:
m1 = tf.constant([[1, 2, 4], [3, 4, 5]])
m2 = tf.reshape(m1, [3, 2])
m1 @ m2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 28],
       [39, 43]], dtype=int32)>

In [38]:
m2 = tf.transpose(m2)

In [39]:
print(f"{m1},{m2}")

[[1 2 4]
 [3 4 5]],[[1 4 4]
 [2 3 5]]


In [41]:
# tf.matmul(m1,m2)

In [3]:
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[2, 0], [1, 2]])
result = tf.matmul(matrix1, matrix2)
print("Matrix Multiplication Result:\n", result.numpy())

Matrix Multiplication Result:
 [[ 4  4]
 [10  8]]


## Simple Neural Network Model

In [2]:
# Importing Libraries
from tensorflow import keras
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Sequential

### Model Building

In [10]:
model1 = Sequential()
model1.add(layer=keras.layers.Input(shape=(3, 1)))
model1.add(layer=(Dense(10, activation="relu")))

In [11]:
model1.add(layer=(Dense(1, activation="sigmoid")))
model1.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 3, 10)          │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 3, 1)           │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model = Sequential(
    [Dense(10, activation="relu", input_shape=(3,)), Dense(1, activation="sigmoid")]
)

In [13]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 10)             │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 51 (204.00 B)

 Trainable params: 51 (204.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.compile(
    optimizer="adam", loss="binary_crossentropy", metrics=[keras.metrics.Accuracy()]
)  # log loss same as logistic

In [15]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 10)             │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 51 (204.00 B)

 Trainable params: 51 (204.00 B)

 Non-trainable params: 0 (0.00 B)

### Training

In [18]:
import numpy as np

X = np.random.rand(100, 3)
y = np.random.randint(0, 2, size=(100,))

In [21]:
print(X.shape)
print(y.shape)
print(y)

(100, 3)
(100,)
[0 1 1 1 0 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 0 1 0 0 1 0 1 1 0
 1 1 0 0 0 1 0 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 0
 1 1 1 1 0 0 1 0 0 1 0 0 0 1 0 1 1 1 0 1 1 0 1 0 0 1]


In [22]:
model.fit(X, y, epochs=5, batch_size=10)

Epoch 1/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.0000e+00 - loss: 0.7020
Epoch 2/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - accuracy: 0.0000e+00 - loss: 0.7005
Epoch 3/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - accuracy: 0.0000e+00 - loss: 0.6993
Epoch 4/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.0000e+00 - loss: 0.6984
Epoch 5/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step - accuracy: 0.0000e+00 - loss: 0.6970


In [75]:
X.shape, y.shape

((100, 3), (100,))

### Predictions

In [23]:
test_data = np.random.rand(5, 3)
predictions = model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


### Saving

In [24]:
model.save("my_model2.keras")

In [25]:
loaded_model = tf.keras.models.load_model("my_model2.keras")
print("Model loaded successfully!")

Model loaded successfully!


### Optimization

In [33]:
# Example
# Defining a custom training loop
optimizer = tf.keras.optimizers.Adam()
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()


@tf.function
def training():
    with tf.GradientTape() as tape:
        predictions = model(X, training=True)
        loss = loss_fn(y, predictions)
    gradients = tape.gradient(loss, model.trainable_variables)
    # print(model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    return loss

In [37]:
# loss = None
# for epoch in range(3):
#     for i in range(100):
#     print(f"Epoch:{epoch},loss:{loss}")

In [28]:
z = np.array([[1, 2, 3, 4], [3, 4, 1, 2]] * 2)
print(f"Shape: {z.shape}, Rank: {z.ndim}")

Shape: (4, 4), Rank: 2


In [29]:
z_tf = tf.constant(z)
z_tf._rank()

2

In [30]:
z_tf1 = z_tf._copy()
r = tf.matmul(z_tf, z_tf1)

In [31]:
z_tf1.ndim

2

In [32]:
tf.rank(z).numpy()

np.int32(2)

## Question

Solve the following system of linear equations using TensorFlow:

x + y + z + w = 13

2x + 3y − w = −1

−3x + 4y + z + 2w = 10

x + 2y − z + w = 1

Ans: x = 2, y = 0, z = 6 , w = 5

In [4]:
# x+y=1
# x-y=0
x = tf.Variable([[1, 1], [1, -1]], dtype=tf.float32)
y = tf.Variable([[1], [0]], dtype=tf.float32)

In [6]:
inverse_coeff = tf.linalg.inv(x)

In [7]:
inverse_coeff

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.5,  0.5],
       [ 0.5, -0.5]], dtype=float32)>

In [8]:
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.,  1.],
       [ 1., -1.]], dtype=float32)>

In [10]:
import pandas as pd

result = tf.matmul(inverse_coeff, y)

In [12]:
print(result.numpy())

[[0.5]
 [0.5]]
